### ISSUE TITLE
WebPage stability index

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#115]
**Short overview**
As a user I want my testcase to only proceed once the SUT is stable.

**Use case**
For example waiting for background tasks on the webpage to be done

**Detailed feature description**
This includes:
- Document ready state
- Pending HTTP requests
- Running animations / transitions
- Pending Promises
- Pending results from `setTimeout`, `setImmediate` and `nextTick` calls
- ContentMutationObservable

The stability index should make element fetching more stable / reliable, but should not add unnecessary delays when elements can be fetched immediately.

**Additional content**
> Please provide any (mandatory) additional data for your desired feature

**Comment by svettwer** [comment]
@s1hofmann would `_pageIsStable` be enough from your perspective to close this one?
