### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#116]
**Short overview**
As a user I want to have proper documentation

**Use case**

**Detailed description**
Requirements:
- Searchable
- Syntax highlighted
- Small sample snippets?

**Additional content**
> Please provide any (mandatory) additional data for your enhancement

**Comment by ZNicoZ** [comment]
Since the basic documentation and a proper layout is implemented.
Further doc issues should be opened within the sakuli.io repo
-> closed
