### ISSUE TITLE
Testsuite UNNAMED

### ISSUE THREAD

**Issue by ZNicoZ** [sakuli/sakuli#121]
**Short summary**
Why doesn´t my CLI output use the testsuite name of the folder nor the name provided in testsuite.properties?
**Detailed question**
![image](https://user-images.githubusercontent.com/7655980/59364621-6d6ba680-8d37-11e9-9b62-a30bd2add8b7.png)
![image](https://user-images.githubusercontent.com/7655980/59364660-7f4d4980-8d37-11e9-81aa-3256be9e1e9d.png)
Content of testsuite.properties:
`testsuite.id=sakuliio-suite`

**Comment by n3k232** [comment]
Same Problem here.
