### ISSUE TITLE
Winston workaround still required?

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#122]
**Short summary**
Sakuli core ships `winston-workaround.ts`

**Detailed question**
A comment in `winston-workaround.ts` mentions the following:

```
// TODO REMOVE WHEN FIXED
// necessary hacks for winston 3.0.0-rc1..
```

Currently we're using the following versions:
```
"winston": "^3.1.0",
"winston-transport": "^4.2.0"
```
So it should be checked whether the workaround is still required or not

**Comment by tnobody** [comment]
No. Neither the workaround file nor the dependencies are required
