### ISSUE TITLE
Multiple Key Types doesn´t work

### ISSUE THREAD

**Issue by ZNicoZ** [sakuli/sakuli#126]
**Version**
2.0.1
**Short overview**
await env.type("P", Key.CMD);
It seems only P will be typed and Key.CMD is ignored.
**Detailed error description**
[Tue Jun 18 2019 14:34:40 GMT+0200 (GMT+02:00)] INFO: Start action type
[Tue Jun 18 2019 14:34:40 GMT+0200 (GMT+02:00)] DEBUG: Typing text 'P' via keyboard

**Comment by tnobody** [comment]
What are you trying to accomplish?
Maybe it is just the logging which doesn't work properly here?

**Comment by ZNicoZ** [comment]
In this specific case I´m trying to open the "print-view" within the browser by hitting CMD+P at the same time. As I understand, this was possible in Sakuli 1 but now doesn´t work with Sakuli 2.

A simple workaround for me was to:
```
await env.keyDown(Key.CMD, Key.P);
await env.keyUp(Key.CMD, Key.P);
```

**Comment by ZNicoZ** [comment]
It works with `await env.type("p", Key.CMD);` or with `await env.type(Key.P, Key.CMD);`
