### ISSUE TITLE
/usr/bin/env: ‘node --no-warnings’: No such file or directory

### ISSUE THREAD

**Issue by marpe4k** [sakuli/sakuli#127]
/usr/bin/env: ‘node --no-warnings’: No such file or directory

Hello,

first sorry for my "newbie" question.
I've followed the getting started guide at 
https://sakuli.io/docs/getting-started
but I can't get Sakuli to work. Trying to execute my first test, I always get the error:

npx sakuli run my-sut
/usr/bin/env: ‘node --no-warnings’: No such file or directory

What did I wrong?
Is there a video available for the getting started setup?

Thanks for help :-)

Regards,
Martin

My environment:
Ubuntu 16.04 xenial server with ubuntu desktop and Google Chrome 75

nodejs v10.15.3 (lts/dubnium) from 
wget https://nodejs.org/download/release/v10.15.3/node-v10.15.3-linux-x64.tar.gz
followed the guide at  https://github.com/nodejs/help/wiki/Installation

 node -v
v10.15.3

ubuntu@sakuli22:/test/sakuli_starter$ npm version
{ sakuli_starter: '1.0.0',
  npm: '6.4.1',
  ares: '1.15.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.34.0',
  node: '10.15.3',
  openssl: '1.1.0j',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.2',
  v8: '6.8.275.32-node.51',
  zlib: '1.2.11' }

ubuntu@sakuli22:/test/sakuli_starter$ npx -v
6.4.1

apt-get install build-essential python libxtst-dev libpng++-dev

as user "ubuntu":

mkdir /test/sakuli_starter
cd /test/sakuli_starter
npm init (default answers accepted)
npm i chromedriver@75.0.0

npm i @sakuli/cli

mkdir my-sut
cd my-sut

touch testsuite.suite
echo "my-testcase/testcase.js https://sakuli.io" >> testsuite.suite

touch testsuite.properties
echo "testsuite.id=my-sut" >> testsuite.properties

mkdir my-testcase
touch my-testcase/testcase.js

vi my-testcase/testcase.js
(async () => {
    const testCase = new TestCase();
    try {
        await _navigateTo("https://sakuli.io");                  // 1
        testCase.endOfStep("Open Landing Page", 5, 10);          // 2
        await _click(_link("Getting started"));                  // 3
        testCase.endOfStep("Navigate to Getting Started", 3, 5);
        await _highlight(_code("npm init"));                     // 4
        testCase.endOfStep("Find npm init code sample");
    } catch (e) {
        await testCase.handleException(e);
    } finally {
        await testCase.saveResult();
    }
})().then(done);

cd /test/sakuli_starter
npm install

npx sakuli run my-sut
ERROR: /usr/bin/env: ‘node --no-warnings’: No such file or directory

**Comment by marpe4k** [comment]
searching deeper, I found there is a problem with the node option "--no-warnings"

/test/sakuli_starter/node_modules/@sakuli/cli/dist
vi index.js
changeing the first line
from:
#!/usr/bin/env node --no-warnings
to
#!/usr/bin/env node
solved my problem in the first step, the sakuli test is running now, but I get all warnings :-(

Is there a workaround available to disable the warnings?

here's my test output:

ubuntu@sakuli22:/test/sakuli_starter$ npm test

> sakuli_starter@1.0.0 test /test/sakuli_starter
> sakuli run my-sut --browser=chrome

  ____            _              _   _
 / ___|    __ _  | | __  _   _  | | (_)
 \___ \   / _` | | |/ / | | | | | | | |
  ___) | | (_| | |   <  | |_| | | | | |
 |____/   \__,_| |_|\_\  \__,_| |_| |_|

========================================

Started execution
→ Started Testsuite my-sut
(node:10963) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
(node:10963) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node:10963) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
(node:10963) ExperimentalWarning: The fs.promises API is experimental
  → Started Testcase UNNAMED
   ⚠ Finished Step Open Landing Page with state Critical..................................................17.703s
   ✓ Finished Step Navigate to Getting Started with state Ok...............................................1.737s
   ✓ Finished Step Find npm init code sample with state Ok.................................................3.469s
   ✓ Finished Step UNNAMED with state Ok.......................................................................0s
  ⚠ Finished Testcase UNNAMED with state Critical..........................................................22.91s
⚠ Finished Testsuite my-sut with state Critical...........................................................22.946s
End execution

**Comment by s1hofmann** [comment]
Hi @marpe4k!

Unfortunately, not every implementation of `env` splits the argument string, which is causing the mentioned problem in the first place.
As a workaround until we release a fix, one can remove the `--no-warnings` argument, as you already did.

Exporting `export NODE_OPTIONS=--no-warnings` it's still possible to hide warnings, which are mostly addressed to developers.
