### ISSUE TITLE
Forwarder for Check_MK Not Working

### ISSUE THREAD

**Issue by dca-adam** [sakuli/sakuli#131]
**Version**
sakuli/cli: 2.0.1 
```
{ sakuli_starter: '1.0.0',
  npm: '6.9.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.9.2',
  icu: '64.2',
  modules: '64',
  napi: '4',
  nghttp2: '1.34.0',
  node: '10.16.0',
  openssl: '1.1.1b',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.29.1',
  v8: '6.8.275.32-node.52',
  zlib: '1.2.11' }
```
**Short overview**
Forwarder for Check_MK is not generating an output file when configured in "testsuite.properties".

**Detailed error description**
Followed the "Getting Started" guide (removed the "--no-warnings" switch from index.js) with no issues and migrated one of our site tests from Sakuli v1.2 to v2.0. In 1.2, each run of a test results in a Check_MK formatted file with testcase results being generated. In v2 this is not happening.

I think this might be related to #51 as the only reference to the Check_MK forwarders I can find (packages/sakuli-legacy/src/loader/legacy-project-properties.class.ts) has this as the template folder property default definition, which would not resolve appropriately:
```
@Property('sakuli.forwarder.template.folder')
sakuliForwarderTemplateFolder: string = "${sakuli.home.folder}/config/templates";` 
```
I also attempted to manually define a template location in testsuite.properties (`sakuli.forwarder.template.folder="/home/sakuli/Documents/sakuli_starter/templates"`), and pulled the Check_MK .twig template files from v1.2 into `sakuli_starter/templates/check_mk` but that didn't have any effect (I don't even know if it would work).

**Steps to reproduce error**
1. Configure a Skauli testcase
2. Add Check_MK forwarder properties to testsuite.properties
3. Run the testcase
4. An output file in Check_MK format should be generated in the specified folder. Currently it is not.

**Additional content**
**testsuite.properties**
```
testsuite.id=sdp                                                                                                                                                                                             
sakuli.forwarder.check_mk.enabled=true                                                                                                                                                                       
sakuli.forwarder.check_mk.spooldir="/home/sakuli/Documents/sakuli_starter/cmkoutput"                                                                                                         
sakuli.forwarder.check_mk.freshness=600                                                                                                                                                                      
sakuli.forwarder.check_mk.spoolfile_prefix=sakuli_suite                                                                                                                                                      
sakuli.forwarder.check_mk.service_description=sakuli_sdp
```

**Comment by ZNicoZ** [comment]
Hi,

the legacy monitoring forwarder is not compatible with Sakuli 2. You can use Sakulis API to implement an interface or you can use the maintained forwarder implementations to various monitoring systems from the enterprise package at:  
[https://sakuli.io/enterprise/](https://sakuli.io/enterprise/)

The enterprise packages will be enriched with more features in the future and include professional support and maintenance.

That´s how we ensure continuous development of Sakuli and a fast and reliable lifecycle.

Kind regards
Nico

**Comment by dca-adam** [comment]
Thanks for the information, that's fair enough.

**Comment by tnobody** [comment]
@dca-adam sorry for the confusion about the properties. We just migrated all possible properties from Sakuli1 into the [property class](packages/sakuli-legacy/src/loader/legacy-project-properties.class.ts). We will remove unnecessary property declaration in the future and move them to dedicated packages.
