### ISSUE TITLE
Add Internet Explorer and Windows Environment Tests in travis

### ISSUE THREAD

**Issue by tnobody** [sakuli/sakuli#136]
**Short overview**

To verify core features and functionality of Sakuli for internet explorer (Webautomation) and windows environment (nut.js implementations). Some automatic checks with IEWebdriver and windows environments should run in the CI System.

~~**Use case**~~

**Detailed description**

research on [matrix builds](https://docs.travis-ci.com/user/build-matrix)
and [windows environments](https://docs.travis-ci.com/user/reference/windows/)

**Comment by s1hofmann** [comment]
Currently Travis does not have display support for platforms other than Linux.
Remote webdrivers won't work either, since we would still require a display on our host running the test.

**Comment by svettwer** [comment]
closed in favor of #331
