### ISSUE TITLE
Missing possibility to configure masterkey via properties or CLI

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#138]
**Version**
2.0.1

**Short overview**
Sakuli currently misses the possibility to configure a masterkey either via CLI option or via property

**Detailed error description**
Sakuli currently only takes masterkeys available via `SAKULI_ENCRYPTION_KEY` into account.
This is just one possibility to provide a masterkey, it should also be possible to provide the masterkey via CLI option or property.

**Additional content**
Sakuli should look for a key in the following order:

CLI option > property > env var

**Comment by tnobody** [comment]
I would propose to introduce a new PropertySource: EnvPropertySource which creates a PropertyMap that reads node.js's `env` variable. This source must be 'installed' to the Project object. 
Final target would be to have somthing like this: 
```typescript
// assuming env.SAKULI_ENC_KEY is somehow set

project.get('SAKULI_ENC_KEY')

class MyProps {
  @StringProperty('SAKULI_ENC_KEY')
  sakuliEncKey: Maybe<string>
}

```
