### ISSUE TITLE
Wrong timestamp log-files

### ISSUE THREAD

**Issue by ZNicoZ** [sakuli/sakuli#147]
**Version**
2.1.0
**Short overview**
Timestamp seems to be off 2 hours.
E.g.: Error-Screenshot taken at 21.30 shows 19.30 as a time.
**Detailed error description**
OSX
**Steps to reproduce error**
force an error

**Comment by tnobody** [comment]
Hi @ZNicoZ,

thank you for this contribution. Could you share some log outputs or screenshots where this time mismatch appears.

thanks in advance

**Comment by ZNicoZ** [comment]
This code produces an error-screenshot with the wrong timestamp.
```
(async () => { 
    const testCase = new TestCase();
    try {
        await _navigateTo("https://sakuli.io");              // 1
        await _click(_div("ThisDivDoesNotExist"));
    } catch (e) {
        testCase.handleException(e);
    } finally {
        testCase.saveResult();
    }

})().then(done);
```

As you can see in the following screenshot, the timestamp in the log is correct, the timestamp of the screenshot filename is incorrect:

<img width="1276" alt="timestamp-Bug" src="https://user-images.githubusercontent.com/7655980/60822851-8c2e5300-a1a6-11e9-8c21-ae7d6a4c02e3.png">

**Comment by ZNicoZ** [comment]
I think the filename uses UTC and the log-output uses GMT+2

**Comment by s1hofmann** [comment]
Yes, `Date#toISOString()` always uses UTC time, which causes the missmatch.
