### ISSUE TITLE
Native highlight throws error on windows 10 ent

### ISSUE THREAD

**Issue by rahulmr** [sakuli/sakuli#167]
**Version** 
`"@sakuli/cli": "^2.1.1-next.13",
    "chromedriver": "^75.0.1"`

`Windows 10 Ent`

**Short overview**
Native `highlight()` does not work on windows. Not tried on Linux

**Detailed error description**
Native `highlight()` function does not work on windows machine.
Gives a state Error, no other details shown in the output window.

Output::
```
Started execution
→ Started Testsuite my-sut
(node:35852) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
(node:35852) [DEP0010] DeprecationWarning: crypto.createCredentials is deprecated. Use tls.createSecureContext instead.(node:35852) [DEP0011] DeprecationWarning: crypto.Credentials is deprecated. Use tls.SecureContext instead.
(node:35852) ExperimentalWarning: The fs.promises API is experimental
  → Started Testcase Sakuli Basic
   → Started Step UNNAMED

   ✓ Finished Step Open Landing Page with state Ok.........................................................6.975s
   ✓ Finished Step UNNAMED with state Ok...................................................................1.817s
  ⚠ Finished Testcase Sakuli Basic with state Error........................................................8.796s
⚠ Finished Testsuite my-sut with state Error...............................................................8.876s
End execution
```

**Steps to reproduce error**
1) Follow instructions on the Getting Started page on a Windows 10 machine.
2) Take a screenshot of the sakuli logo on the home page i.e. https://sakuli.io
3) Check the script below for modifications.

**Additional content**
> Please provide any (mandatory) additional data to reproduce the error (Code, Config, Dockerfiles etc.)

```javascript
(async () => {
    const testCase = new TestCase("Sakuli Basic");
    testCase.addImagePaths("../images");

    try {
        await _navigateTo("https://sakuli.io");                  // 1
        testCase.endOfStep("Open Landing Page", 15, 20);        // 2        
        const screen = new Region();
        await screen.find("sakuli.png").rightClick().click(); // WORKS
        await screen.find("sakuli.png").highlight(2); // DOESN'T WORK
        testCase.endOfStep("Right Click Sakuli Logo", 10, 15);
        await _click(_link("Getting started"));                  // 3
        testCase.endOfStep("Navigate to Getting Started", 8, 15);
        await _highlight(_code("npm init"));                     // 4
        testCase.endOfStep("Find npm init code sample");
    } catch (e) {
        await testCase.handleException(e);
    } finally {
        await testCase.saveResult();
    }
})().then(done);


```

**Comment by s1hofmann** [comment]
Hi @rahulmr, thanks for your contribution!

Unfortunately, Sakuli does not yet include native `highlight` functionality.
In your test log you should see a `Not Implemented` error message, since we are still working on a stable, cross-platform solution for native highlights.

We can not yet tell when this feature will be finished, but I'll update this issue as soon as there are news regarding native highlight.

**Comment by rahulmr** [comment]
@s1hofmann Thanks for your reply. My bad I didn't check the code. Actually, I thought you have not tested on Windows 10. 
Also, not related to this issue, wanted to know about the reporting. I do not see any documentation on how reports will be generated.
Is it that we need to use sakuli ui?
Where shall I check if I want reporting or create my own csv or json file showing the take taken by each step?
I have few suggestions / questions, shall I create issues for the same?

**Comment by s1hofmann** [comment]
Hi @rahulmr,

in case you have open questions, please feel free to open additional issues and we will discuss your topics there!

Once again, thank you for engaging in our growing community!

**Comment by svettwer** [comment]
Analysis required first.

**Comment by svettwer** [comment]
After exploring the opencv4nodejs API, I've found `import { Mat } from "opencv4nodejs-prebuilt";`.

The class `Mat` provides a `drawRectangle` function. This should allow us to create an `highlight` function based on a `Region`.
