### ISSUE TITLE
How to run a pure native app test

### ISSUE THREAD

**Issue by rahulmr** [sakuli/sakuli#169]
**Short summary**
How to create and run on Native app test?

**Detailed question**
In my case, I do not want to run any browser or launch any url.
Only perform tests on a Windows Desktop application.
Can this be done? Any examples?

**Comment by ZNicoZ** [comment]
Hi, it can be done with image matching, you can find some examples here: [sakuli.io/testing](https://sakuli.io/testing/)

**Comment by rahulmr** [comment]
@ZNicoZ Already gone through it, it will still launch the browser if I have chrome as default browser. I want something like browser=none and then only execute tests which are based on image matching.
Is it possible run windows only tests or provide none option for browser as enhancement?

**Comment by s1hofmann** [comment]
Hi @rahulmr, thank you for contributing to Sakuli!
As of now, Sakuli assumes a web / native combination setup, so it'll always launch a browser on startup.

A possible workaround would be to configure Chrome to start in headless mode:

> `testsuite.properties`

```
selenium.chrome.arguments=--headless
```

If you want to completely skip the browser / webdriver part, please open a separate issue with an enhancement request, so we can discuss further details there.

Best regards

Simon

**Comment by rahulmr** [comment]
Hi Simon,
`selenium.chrome.arguments=--headless`
does not work for me. Could you please check at your end? Thanks

**Comment by rahulmr** [comment]
Seems like issue is already open #166

**Comment by rahulmr** [comment]
@s1hofmann open new issue #171 for enhancement request to have browser option as `none`

**Comment by tnobody** [comment]
Close this issue because we will implement it in #171
