### ISSUE TITLE
How to generate html reports?

### ISSUE THREAD

**Issue by rahulmr** [sakuli/sakuli#170]
**Short summary**
How to generate html reports?

**Detailed question**

We need to compare time taken by each step in a scenario?
Is there any way to generate proper html reports or some csv files?
The generated html report should be shareable or say should be a single file html or htm file with pass and fail data along with elapse time for every step.

**Comment by s1hofmann** [comment]
Hi @rahulmr,

we just discussed the reporting topic.
We agree that Sakuli should provide reporting in some way, but we might not stick with HTML output.

We rather thought about providing [Maven SureFire Reports](https://maven.apache.org/surefire/maven-surefire-report-plugin/)

The reasoning for this are the following:

- Wide use of Surefire reports
- Great tool support
- 3rd party tooling to generate e.g. HTML reports

We will open a separate issue for test reports.

Best regards

Simon

**Comment by rahulmr** [comment]
Thanks Simon!!
I was also thinking if as of now is it possible to get report or status as step and elapse time in a csv file.
It can help us to check performance of an application.

**Comment by rahulmr** [comment]
May be you can also check mochaawesome reporter [here](https://github.com/fijijavis/wdio-mochawesome-reporter)

**Comment by rahulmr** [comment]
I also saw that [jest-stare](https://dkelosky.github.io/jest-stare/) and [jest-html-reporters](https://github.com/Hazyzh/jest-html-reporters) are also good option when we use jest as testing framework and typescript.

**Comment by svettwer** [comment]
Even if this issue is pretty old:
Forwarding measurements from test execution can be achieved using Sakuli Forwarder. 
Currently Icinga2, OMD/Gearman, CheckMK and Prometheus are supported. All of them are part of the Sakuli Enterprise packages. 
For more information, please have a look at https://sakuli.io/#enterprise.

It is currently not planned to add any file based reports beside enterprise forwards.
