### ISSUE TITLE
How to click image with offset?

### ISSUE THREAD

**Issue by rahulmr** [sakuli/sakuli#173]
**Short summary**
How to native click an image with offset?

**Detailed question**
I want to click an image with offset like we do it in Sikuli
In sikuli or [TagUI](https://github.com/kelaberetiv/TagUI), we can click image with offset.
TagUI code
`find('image.png').offset(0,-15).click();`
Sikuli
`click('image.png').targetOffset(0, -15)`
So what is the equivalent code for the same in Sakuli2

**Comment by s1hofmann** [comment]
Hi @rahulmr,

you could achieve this using the following snippet:

```js
await screen.find("image.png").move(0, -15).click();
```

For further reference you can also check https://sakuli.io/apidoc/sakuli-legacy/interfaces/region.html

**Comment by s1hofmann** [comment]
@rahulmr Have you been able to perform clicks with offset?

**Comment by s1hofmann** [comment]
Closing due to no response. Feel free to re-open in case of further problems.

**Comment by rahulmr** [comment]
@s1hofmann Thanks I was able to work the way you suggested. I was away from work so could not reply :)
