### ISSUE TITLE
Refactor debug logging into utility package

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#194]
**Short overview**
Reduce code duplication for log output

**Detailed description**
In our code base we're often using a construct similar to the following snippet:

```
logDebug(message: string, ...data: any[]) {
    ifPresent(this.logger, log => log.debug(message, ...data));
}
```

In order to reduce code duplication, these snippets should be refactored in a re-usable way an made available in e.g. @sakuli/commons

**Comment by cliffle** [comment]
With the current Typescript version we are using, you can use the Elvis operator instead of the construct, so there is no need to build this snippet into @sakuli/commons
