### ISSUE TITLE
Process list support

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#195]
**Short overview**
As a user I'd like to check whether a process is still running or not.

**Use case**
Wait conditions to await asynchronous tasks

**Detailed feature description**
In a scenario where a testcase triggers some external action, Sakuli should be able to wait until completion by e.g. watching for running processes. 

In order to do so, it would require to have a cross-platform way of retrieving a list of processes to define a condition when to continue.

**Comment by betrZHAW** [comment]
I would also be interested in such a feature. Is the implementation already planned?

**Comment by svettwer** [comment]
We're currently on it. :wink:

**Comment by svettwer** [comment]
In our opinion, process management of the underlying operating system is not in scope of Sakuli as an End-2-End Application Testing, Monitoring and RPA-Tool. Therefore we'll not add this functionality to Sakuli. We recommend to manage async processes started beside the tests using the node API.

BR
Sven

**Comment by ZNicoZ** [comment]
There are possibilities to achieve this using additional npm packages that generate process list of Windows / Linux environments. 
As this is an edge-case we will not implement this approach in Sakuli. 

Nevertheless, we can provide information and how-tos, please contact us via https://sakuli.io/enterprise/
