### ISSUE TITLE
Log levels

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#201]
**Short overview**
As a Sakuli user I want to be able to specify a log level to filter relevant content.

**Use case**
Hiding e.g. debug logs from output on test runs.

**Detailed description**
Each Sakuli log event has a certain level.
When debugging errors, this one might be interested in every log event, especially DEBUG ones.
For standard test execution, DEBUG logs are quite verbose and pollute the log.
By applying a configurable log level, these logs could be neglected for output.

**Additional content**
> Please provide any (mandatory) additional data for your enhancement

Log hierarchy:

ERROR > WARN > INFO > DEBUG

**Comment by WWIJP** [comment]
Pleas make it possible that we see the output in the cli and the logs. Thanks!
