### ISSUE TITLE
API of Sakuli 2 (mix of Sakuli 2 and Sakuli 1)

### ISSUE THREAD

**Issue by WWIJP** [sakuli/sakuli#208]
**Short overview**
The API of Sakuli 2 has to be only for Sakuli 2 and not a mixture of different pages.
The Sakuli 2 API page is missing the "_highlight" method:
https://sakuli.io/apidoc/sakuli-legacy/interfaces/accessorapi.html

**Use case**
API

**Detailed description**
The API of Sakuli 2 has to be only for Sakuli 2 and not a mixture of different pages.
The Sakuli 2 API page is missing the "_highlight" method:
https://sakuli.io/apidoc/sakuli-legacy/interfaces/accessorapi.html

**Additional content**
Please put all the API functions and methods, ets. in one page, like:
https://sakuli.io/apidoc/sakuli-legacy/interfaces/accessorapi.html

**Comment by WWIJP** [comment]
A API mix is not necessary because Sahi or Sikuli are not a component any more of Sakuli 2.

**Comment by ZNicoZ** [comment]
Here you can find an overview of the APIs for DOM based Testing:
https://sakuli.io/apidoc/sakuli-legacy/globals.html
![image](https://user-images.githubusercontent.com/7655980/64190368-7ff90600-ce76-11e9-927f-59c3089bd8d3.png)

You will find Accessor APIs here - use them to search for methods to access an element (like a header, a link, radio buttons etc.):
https://sakuli.io/apidoc/sakuli-legacy/interfaces/accessorapi.html
![image](https://user-images.githubusercontent.com/7655980/64190513-de25e900-ce76-11e9-9120-b270474dad13.png)

Use the fetch-API for collecting elements/data:
https://sakuli.io/apidoc/sakuli-legacy/interfaces/fetchapi.html
![image](https://user-images.githubusercontent.com/7655980/64191005-d3b81f00-ce77-11e9-98b5-02a5e8502de4.png)

And finally the Action API to do something like highlighting / clicking etc: 
https://sakuli.io/apidoc/sakuli-legacy/interfaces/actionapi.html
![image](https://user-images.githubusercontent.com/7655980/64191097-0530ea80-ce78-11e9-9ba6-b5c31d53276d.png)

Hope this helps.

**Comment by WWIJP** [comment]
Hello, that looks good! Is there a search possibility available? We didn't found one at the main page (https://sakuli.io/apidoc/sakuli-legacy/) or at the others. This would help a lot! Thanks

**Comment by tnobody** [comment]
@WWIJP you can find a small "magnifying glass" in the toolbar at the top which should help you.
This are auto generated docs from the code, we are working on a more obvious structure and better integration into "main-layout" from sakuli.io as well as more content for the methods.
I hope it'll help you anyway in the mean time.

Br
