### ISSUE TITLE
Screenshot Picture Name

### ISSUE THREAD

**Issue by WWIJP** [sakuli/sakuli#210]
**Short overview**
The screenshot picture name is not showing the problem name

**Use case**
Identifying the problem faster by getting the screenshot picture name

**Detailed description**
For us as users would it be the best if the screenshot picture name would include the step name (if given) and the problem of the method or the name of the picture which was not found, etc.

**Additional content**

**Comment by tnobody** [comment]
Hello @WWIJP,

thank you for your contribution. 

I think that is basically a good idea. Unfortunately the format of errors changed from Sakuli v1 which makes it hard to fit them generically into a filename (which has some restrictions).

@s1hofmann do you see any handy approach here?

Br

**Comment by svettwer** [comment]
closed after a nearly a year of inactivity.
The log outputs and error messages in sakuli have been improved in that time. If the issue still occurs, please consider to open a new one with updated information
