### ISSUE TITLE
Pure Browser Testing

### ISSUE THREAD

**Issue by m-kappes** [sakuli/sakuli#213]
**Short overview**
Pure Browser Testing without the need to start the native Tests

**Use case**
Use Sakuli only for testing a Website. I.e. in Gitlab without the need for a display.
Similar to #171 just with the web testing instead of native testing

**Detailed description**
The possibility to run only the webtests in a headless Browser.

**Comment by s1hofmann** [comment]
We will have to investigate whether there's a programmatic way to disable native features without modifying dependencies.
We will use this issue to discuss our findings.

**Comment by svettwer** [comment]
Idea: opt-out for native desktop dependencies

**Comment by tnobody** [comment]
I'll just start to dump some thoughts before I start deeper analysis:

The Idea to opt-out from native-desktop dependencies sounds good and obvious at first glance. I think a big challenge here could be that the native functions are deeply integrated into Legacy-DSL.
In some cases, it is pretty obvious e.g. `Region`-class which could be just be injected with a dummy (like the dummy SahiAPI).
But there are some cases where the native functions are a bit more "hidden":
- `TestCase` class (when taking screenshots)
- `Environment`-class has a lot of ambiguous concerns: On one hand, it gives access to ENV-vars, Secrets, Properties, etc, on the other hand, it gives some access to native functionality e.g. ClipBoard, Type, etc.

IMHO I would say it is pretty complex to handle all these cases within the legacy DSL from a developer perspective. And I see a lot of curios users when some parts of the DSL are working and some do not.

Maybe we should discuss this aspect before we investigate in some technical solutions to "opt-out" from native functionality.
