### ISSUE TITLE
Problem: Chrome via VNC: Proxy settings are not possible to set manually

### ISSUE THREAD

**Issue by WWIJP** [sakuli/sakuli#216]
**Version**
2.1.2

**Short overview**
Chrome via VNC: Proxy settings are not possible to set manually

**Detailed error description**
Chrome via VNC: Proxy settings are not possible to set manually
If we want to set the proxy settings, ther comes the message:
When running Chromium under a supported desktop environment, the system proxy settings will be used. However, either your system is not supported or there was a problem launching your system configuration.

But you can still configure via the command line. Please see man chromium-browser for more information on flags and environment variables.

==> In Firefox it is possible and works like expected

**Steps to reproduce error**
Start Container, VNC and Chrome via GUI, navigate to proxy settings

**Comment by ZNicoZ** [comment]
This repository is intended for Sakuli Core (Open-Source part of Sakuli).
Your question is referring to an enterprise feature for which there are specific support channels. Please use the respective channels with an active subscription. Thank you.
