### ISSUE TITLE
Splitting up @sakuli/legacy

### ISSUE THREAD

**Issue by tnobody** [sakuli/sakuli#238]
**Short overview**

Right now we combine the domains of native and web testing into a single package `@sakuli/legacy` which has a lot of responsibilites and dependencies.

I'm thinking of a somehow bigger destruction into several packages (suggestion):

- `@sakuli/web-shell`: Provides all utilities around selenium as reusable components
- `@sakuli/native-shell`: Provides all utilities around nut.js as reusable components
- `@sakuli/legacy-sahi-api`: Provides the implementation of Sahi DSL (using `@sakuli/web-shell`)
- `@sakuli/legacy-native-api`: Provides the DSL implementation for:
  - `Environment`
  - `Key`
  - `MouseButton`
  - `Region`
- `@sakuli/legacy-api`: Provides DSL implementation for: 
  - `TestCase`
  - `Logger`
- `@sakuli/legacy`: Is meant to be a shell for `@sakuli/legacy-api` `@sakuli/sahi-api` and `@sakuli/native-api` so that nothing will change for the users

This will not necessarily require a lot of rewrites since there is no new implementation (beside a little glue code).

**Use case**

Reuse Selenium enhancements in other DSLs.

**Comment by ZNicoZ** [comment]
In this process, let´s get rid of any sahi / sikuli reference and change the wording to either just legacy or sakuli1

**Comment by svettwer** [comment]
IMHO, we have no dedicated issue with `@sakuli/legacy` handling so much responsibilities. Yes, it is some kind of a design flaw and yes, a split up might be required in the future as a requirement for a different, more functional issue. I think, this issue should be closed.

**Comment by svettwer** [comment]
We agreed to close this issue as we have no problem with `@sakuli/legacy` handling so much responsibilities.
