### ISSUE TITLE
Enhance documentation for Action-API and Fetch-API

### ISSUE THREAD

**Issue by ZNicoZ** [sakuli/sakuli#241]
Add examples and description text to the following API docs:

- ~Global~
- ~Accessor~
- Fetch
- Action

**Comment by tnobody** [comment]
Hi @ZNicoZ 

can you specify what is missing in accessor api and what is meant with global?

**Comment by ZNicoZ** [comment]
It was only a list from my mind to cover the most important APIs

**Comment by svettwer** [comment]
Scope is limited to fetch and action API, right?
