### ISSUE TITLE
Add Typescript support

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#245]

**Comment by s1hofmann** [comment]
Some things I noticed when running the latest `@next` release:

- `@sakuli/legacy-types` is private by default
- The `enable-typescript` command uses the default tag, thus is not able to install `@next` types
- `@sakuli/rollup-hooks` only specified a TypeScript devDependency, this causes errors at runtime. We could either change the dependency type, or install TS via `enable-typescript` command

**Comment by tnobody** [comment]
I made bug issues for all of your points: #253, #254, #255
