### ISSUE TITLE
@sakuli/legacy-types are not published

### ISSUE THREAD

**Issue by tnobody** [sakuli/sakuli#253]
**Version**

2.1.4-next.7

**Short overview**

Issued in: https://github.com/sakuli/sakuli/issues/245#issuecomment-543530614

Regarding to the Build process the package @sakuli/legacy-types should be published ([logs](https://travis-ci.com/sakuli/sakuli/builds/132423034#L4218-L4236))

But I'm neither able to install them with `npm i @sakuli/legacy-types@next` nor find them on [npm.com](https://www.npmjs.com/search?q=%40sakuli)

**Additional content**

Could it be that we first need at least one @latest release?

**Comment by ZNicoZ** [comment]
Acc. Crit:
- package is publicly installable from npmjs.com with `npm i @sakuli/legacy-types`

**Comment by svettwer** [comment]
to be fixed on npmjs.com in package management
