### ISSUE TITLE
`enable-typescript` command should install @sakuli packages with the same version as in project

### ISSUE THREAD

**Issue by tnobody** [sakuli/sakuli#254]
**Version**

2.1.4-next.7

**Short overview**

Issued in https://github.com/sakuli/sakuli/issues/245#issuecomment-543530614

When using the command `sakuli enable-typescript` it installs `@sakuli/legacy-types` by running `npm i @sakuli/legacy-types`. This could lead to some conflicts when using a verison of Sakuli that is either older than `@latest` or `@next`.

**Additional content**

The command should determine the version of the current Sakuli intallation by either:
- looking at the `pacakge.json`
- using output from `sakuli --version`

The latter approach would guarantee that we get the same version of Sakuli that the user is using because the command must eventually be started with the `sakuli` command.

**Comment by ZNicoZ** [comment]
Acc. Clit:
- typescript installation is automatically versioned in consistency with sakuli installtion
