### ISSUE TITLE
Typescript is not installed when enabling typescript-support

### ISSUE THREAD

**Issue by tnobody** [sakuli/sakuli#255]
**Version**

2.1.4-next.7

**Short overview**

Issued in: https://github.com/sakuli/sakuli/issues/245#issuecomment-543530614

> @sakuli/rollup-hooks only specified a TypeScript devDependency, this causes errors at runtime. We could either change the dependency type, or install TS via enable-typescript command

**Additional content**

I would recommend to install typescript when running `enable-typescript` command. The package dont have to provide a possibly unnecessary dependency.

_Workaround_: Right now a user (or tester for ts-support) could install it manually `npm i typescript`

**Comment by ZNicoZ** [comment]
Acc Crit: 
- Typescript is automatically installed in project via enable-typescript command
- Version of Typescript: to evaluate
- Global / Package installation consistency

**Comment by tnobody** [comment]
We should wait until #289 is merged because same files need to be edited
