### ISSUE TITLE
Control if Sakuli should create new browser sessions within Testsuite

### ISSUE THREAD

**Issue by tnobody** [sakuli/sakuli#260]
**Short overview**

As a tester i want to control if Sakuli creates a new webdriversession for each test-file to prevent to keep between testcases

**Use case**

When testing an SUT within a testsuite with several testcases it might or it might not be useful that all testcases run within a single webdriver session.

The current behavior is that Sakuli keeps the session open during the whole execution of a testsuite.

This causes different sideeffects:
- cookies and other local stored data persists between testcases (an login might persist between testcases for example)
- When navigating to the same page as the browser is currently navigated, no refresh might be triggered
- Depending on the browser some effects with the hash (`#`) part of an url could be strange.

From a pure academic perspective every testcase should be independent on it's own, however it could be useful in real world E2E scenarios to work on an existing state (like a logged in user).

**Comment by svettwer** [comment]
We agree that this should be done. Now we have to find out how!

**Comment by svettwer** [comment]
Seems to be pretty easy.
We just need to create a new driver instance in the `legacy-liefcycle-hooks.class.ts` in the `beforeRunFile` handler. The driver creation is a responsibility of the `legacy-liefcycle-hooks.class.ts` anyways and we are able to react on new file processings in Sakuli.

https://github.com/sakuli/sakuli/blob/61ac623bd7ec5aa676f3d7747bcaa320b465347b/packages/sakuli-legacy/src/context/legacy-lifecycle-hooks.class.ts#L83-L93

Something like this should do the trick.

```typescript
  async beforeRunFile(
    file: TestFile,
    project: Project,
    ctx: TestExecutionContext
  ) {
    this.currentFile = file.path;
    this.currentProject = project;
    this.currentTest = dirname(
      await fs.realpath(join(project.rootDir, file.path))
    );
   this.driver = this.builder.build()
   await this.driver.manage().window().maximize();
  }

  async afterRunFile(
    file: TestFile,
    project: Project,
    ctx: TestExecutionContext
  ) {
    const { name } = parse(file.path);
    ifPresent(ctx.getCurrentTestCase(), (ctc) => {
      if (!ctc.id) {
        ctx.updateCurrentTestCase({ id: name });
      }
    });
   this.driver.close();
  }
```

**Comment by svettwer** [comment]
Acceptance criteria:

- [ ] add optional property to deactivate the reuse of the browser
- [ ] if reuse browser property is false then create a new browser
- [ ] if reuse browser property is true (which is default) no new browser is created and the existing browser instance is reused
- [ ] Add major version remark: reuse browser should default to false in new major version of Sakuli
