### ISSUE TITLE
node 12 support

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#266]
**Short overview**
As a Sakuli user I want to be able to use Sakuli with the latest node lts version, lts/erbium.

**Use case**
Proper long term support and security updates.

**Detailed description**
With the most recent lts version of node, lts/erbium, Sakuli needs to update its dependency on @nut-tree/nut-js.
Since nut.js relies on nan modules, v1.3.0 is not compatible with node v12.
nut.js v1.3.1 adds support for node 12.

Acc.Crit:
- [ ] E2E Tests on Win/Lin/Mac/Container + a couple of customer projects
- [ ] document known issues on Mac within docs
- [ ] prepare docs branch accordingly

**Comment by svettwer** [comment]
@ZNicoZ: Required for customer project.

**Comment by tnobody** [comment]
Also created an issue for the container: https://github.com/sakuli/sakuli-docker/issues/32
