### ISSUE TITLE
Bootstrap: Install latest Sakuli version in project

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#267]
**Short overview**
As a Sakuli user I want the testsuite generator to install the latest Sakuli version for me

**Use case**
- Automated installation of latest Sakuli version
- Ready to use project, no initial, manual `npm i` required

**Detailed description**
When bootstrapping a new Sakuli project including a `package.json` via the CLI command implemented in #22, a fixed Sakuli version is listed as dependency. This requires an update on each Sakuli release. Additionally, one would have to run an initial `npm i`, to install the listed dependencies before running a test.

Another way of dealing with this dependency would be to not explicitly list the Sakuli dependency in the generated `package.json`, but to execute `npm i @sakuli/cli` in the bootstrapped project directory. This way, we automatically install the latest Sakuli version.

**Additional content**
> Please provide any (mandatory) additional data for your enhancement

Acceptance criteria:
- Project is bootstrapped
- When bootstrapping a project including a `package.json` (`npx @sakuli/cli@next create project /path/to/suite suiteName --package`), generated `package.json` does not list dependencies
- When bootstrapping a project including a `package.json` (`npx @sakuli/cli@next create project /path/to/suite suiteName --package`), Sakuli is installed via npm after bootstrapping the overall project structure

**Comment by svettwer** [comment]
As mentioned in #297 

>A possibility to solve this would be an adaption of the version determination strategy introduced in #289.
