### ISSUE TITLE
Add option to init git in create project command

### ISSUE THREAD

**Issue by tnobody** [sakuli/sakuli#269]
**Short overview**

As a User I want to have an option to initialize a git repo in the project root with a proper `.gitignore` file to avoid manual setup.

**Use case**

see description

**Detailed description**

The `create project <PATH>` should accept an optional parameter `--git` which
- initializes a local git repo in `<PATH>`
- create a `.gitignore`file in `<PATH>` with the following contents:
```
_logs/
*.steps.cache
```
when set

**Comment by svettwer** [comment]
We agreed that this feature comes with a bunch of stuff to consider.
- How to add remotes?
- What about `--package` suites combined with `--git`. Where to create the repo
- Git-Workflow of today: Most times, you create a repo on your git provider, check it out and init then

At the end, we decided to close this issue for now.
