### ISSUE TITLE
Autodiscovery for presetprovider

### ISSUE THREAD

**Issue by tnobody** [sakuli/sakuli#276]
**Short overview**

As a User I dont want to add each presetprovider package (e.g. forwarder) manually in the package.json

**Use case**

Make it easier to use sakuli ecosystem

**Detailed description**

We could use similir approach as Typedoc does for it's plugin-autodiscovery: https://github.com/TypeStrong/typedoc/blob/master/src/lib/utils/plugins.ts#L72

**Comment by svettwer** [comment]
@cliffle Even when all PRs are merged, we should perform E2E tests including enterprise forwarders to ensure the auto discovery works as expected with the new release.
