### ISSUE TITLE
Resolve crypto deprecation warnings

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#284]
As a Sakuli developer, I want to get rid of deprecation warnings, to keep the software up to date and secure.

![image.png](https://images.zenhubusercontent.com/5bd84806d2996a6154b73678/72ce9347-e007-4956-ae78-5e4213df3278)

This warnings show up every time Sakuli starts. The story requires refinement to find the root cause. 

**Workaround**
To suppress the warning, set `NODE_NO_WARNINGS=1` as environment variable.

**Comment by s1hofmann** [comment]
Root cause:

- Wildcard include of `crypto` module in `@nut-tree/secrets`

Solution:

- Update depencency `@nut-tree/secrets` in `@sakuli/legacy` to v4.0.2
- Specify an encryption algorithm when using `secret.encrypt` or `secret.decrypt`. The algorithm used by Sakuli is `Algorithm.AES128CBC`
