### ISSUE TITLE
sakuli shell completion

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#293]
As a shell affine sakuli user, I would like to be able to user shell completion to be able to navigate the sakuli CLI more efficient.

**Comment by cliffle** [comment]
Hi,

I just had a look into the shell completion for Sakuli. yargs, the tool we are using for the command line, offers a [completion function](https://github.com/yargs/yargs/blob/master/docs/api.md#completioncmd-description-fn), which supports bash and zsh.

**Comment by svettwer** [comment]
I've experimented with this now for round about three hours. It is absolutely possible to create an auto completion by using yargs but Sakuli breaks this functionality but printing a lot of information every time it starts.

This is mainly because of the changes in #338. They add `console.debug` calls which is just an alias to `console.log` and therefore always printed. ([source](https://nodejs.org/api/console.html#console_console_debug_data_args))

So first, we'd have to ensure that Sakuli boots up silently. This is dramatically expanding the scope of this issue. IMHO, we should not add the auto completion because of the mentioned complexity. I'd rather suggest to improve the CLIs help information to guide the user through the different options and commands.

**Comment by svettwer** [comment]
team agreed
