### ISSUE TITLE
CLI does not report unknown commands

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#294]
As a sakuli user, I want the CLI to report unknown commands, so that I'm able to know that I am doing something wrong.

![image](https://user-images.githubusercontent.com/25754312/70308634-f73e8d00-180b-11ea-9513-b6941fea982c.png)
_In addition: A return code other than 0 would be great_

**Comment by tnobody** [comment]
There is  a discussion about this topic in the yargs repo: https://github.com/yargs/yargs/issues/287 (also with some workarounds)
