### ISSUE TITLE
Fix SonarCloud setup

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#30]
Our current setup does not correctly process coverage reports, thus Sonarcloud reports a testcoverage of 0%.

**Comment by tnobody** [comment]
I close this issue since the PR is successfully merged

**Comment by svettwer** [comment]
Unfortunately it is not, because the reports are currently overwritten. So only the coverage of one module is in consideration.

**Comment by tnobody** [comment]
Ahh sorry just saw that this issue actually belongs to the Test-Coverage not "only SonarCloud"

**Comment by svettwer** [comment]
No problem! =)
Yeah I think the report problem is in scope.

**Comment by s1hofmann** [comment]
As far as I can tell, #54 should have resolved the issue, so I'll close it.
If I'm mistaken, feel free to re-open.
