### ISSUE TITLE
Wait until Iframes are loaded completely

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#315]
When testing a website using Iframes, it might be the case that the Sakuli test continues, even if the Iframe has not been loaded completely. This causes tests to fail.

Acceptance criteria:
- [ ] Sakuli tests don't error because of long-loading Iframes

**Comment by ZNicoZ** [comment]
You could use 
```
await _wait(timeout, () => _isVisible(_iframe(nameOfIframe)));
```
to wait for the actual frame and then you could check for an element within the frame
```
await _wait(timeout, () => _isVisible(_elementWithinFrame()));
```
to ensure the content is loaded.

**Comment by svettwer** [comment]
Yes :+1:
