### ISSUE TITLE
normaliseIdentifierString eliminating regex

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#318]
As a software developer, I want to fix and test `normaliseIdentifierString` so that given regex are not eliminated and replaced with a wildcard regex.

Acceptance criteria:
- [ ] `normaliseIdentifierString` is not eliminating regex
- [ ] `normaliseIdentifierString` is unit test covered (maybe a regex utils module makes sense)

**Comment by s1hofmann** [comment]
Further refinement (e.g. regex example) required

**Comment by cliffle** [comment]
It looks like any regular expression within a string (e.g. `"/just an example/"`) returns an empty string.

The following test should fail but it doesn't: 
```
(async () => {
  const testCase = new TestCase("sample test");
  try {
    await _navigateTo("https://sakuli.io");
    await _highlight(_link("/this does not exist/"));
    await testCase.endOfStep("example step");
  } catch (e) {
    await testCase.handleException(e);
  } finally {
    testCase.saveResult();
  }
})();
```
