### ISSUE TITLE
Bootstrap defaults

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#32]
When Sakuli is executed via globally installed package it lacks configuration (presetProvider), which would be provided via `package.json`.
Without such a presetProvider Sakuli is unable to process any tests.

As a first step to mitigate this problem, Sakuli could provide a default `presetProvider`, e.g. `@sakuli/legacy`.
For the future we could consider a loader mechanism to determine a suitable `presetProvider`.

**Comment by tnobody** [comment]
I close this issue since the PR is successfully merged
