### ISSUE TITLE
Print and log information about loaded presets

### ISSUE THREAD

**Issue by tnobody** [sakuli/sakuli#320]
As a User, I want to see information about the preset-providers which are loaded in a Sakuli test case.

Acc. Crit:
- [ ] For each successfully loaded preset Provider the User sees at least the package name and version (derived from package.json of preset-provider)
  - [ ] Information should be logged (at debug level?)
  - [ ] information should be printed on CLI

**Comment by svettwer** [comment]
Done with #338
