### ISSUE TITLE
Colliding interfaces in selenium configuration

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#328]
According to [create-driver-from-project.function.ts](https://github.com/sakuli/sakuli/blob/05cf4ce6b73622d1f46267d4c9ec1a6838c85606/packages/sakuli-legacy/src/context/selenium-config/create-driver-from-project.function.ts#L47), `seleniumProperties.loggingPrefs` is of Type `Maybe<IPerfLoggingPrefs>`, while `builder.setLoggingPrefs(prop)` expects `props` to be `logging.Preferences|{}`.
Both interfaces don't match so a configuration of this property would crash as far as I can see. 

Acceptance criteria:
- [ ] Config interfaces match

**Comment by svettwer** [comment]
requires further anlysis

**Comment by cliffle** [comment]
As far as I understand, changing the colliding interface isn't the only thing we need to change to get to the selenium logs.
Firstly, we need to set the logging level for the appropriate logging type, e.g.:
```typescript
    const pref = new logging.Preferences()
    pref.setLevel(logging.Type.DRIVER, logging.Level.ALL);
    pref.setLevel(logging.Type.PERFORMANCE, logging.Level.ALL);
    pref.setLevel(logging.Type.CLIENT, logging.Level.ALL);
    pref.setLevel(logging.Type.BROWSER, logging.Level.ALL);
    pref.setLevel(logging.Type.SERVER, logging.Level.ALL);
    builder.setLoggingPrefs(pref);
```

Secondly, we need to collect the logs after the test execution with e.g.
```typescript
    const logs = driver.manage().logs();
    const types = await logs.getAvailableLogTypes();
    for (let logType of types) {
      await Logger.logInfo(logType)
      const logEntries = await logs.get(logType);
      for (let logEntry of logEntries) {
        await Logger.logInfo(logEntry.message);
      }
    }
```
I added this in the `finally` block of the test script and got the following selenium log output:
```
[Thu Dec 31 2020 08:50:45 GMT+0100 (Central European Standard Time)] INFO: browser
[Thu Dec 31 2020 08:50:45 GMT+0100 (Central European Standard Time)] INFO: https://sakuli.io/favicon.ico - Failed to load resource: the server responded with a status of 404 ()
[Thu Dec 31 2020 08:50:45 GMT+0100 (Central European Standard Time)] INFO: driver
```

**Comment by svettwer** [comment]
It would be great if you could propose a solution for what you found out. :+1: :rocket:

**Comment by cliffle** [comment]
My proposal is to enable all logging types at once so therefore no further configuration is needed other than to enable the Selenium log. Also, it should be collected automatically after the test execution and returned on the debug level.

**Comment by svettwer** [comment]
A logging integration does not seem to be that easy as there are open issues concerning logging integration in gecko driver at least...
