### ISSUE TITLE
Re-evaluate CI system

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#331]
We are currently hitting limits of what is possible with Travis.

https://github.com/sakuli/sakuli/pull/330 introduces E2E tests on CI, but unfortunately, Travis is not able to run Windows GUI tests on CI.
This limits our E2E tests to only Linux and macOS.

It is also not clear, if Travis will upgrade its Windows hosts in the future, so we should re-evaluate possible alternatives like:

- [ ] GitHub Actions
- [ ] Appveyor

Alternatives should be compared to Travis regarding:

- Monthly cost
- Use of private repos
- Plattform support
- Technical capabilities (matrix builds etc.)

**Comment by tnobody** [comment]
What do you think about giving [circleci](https://circleci.com/) a shot?
As I know it gives the possibility to run and develop the Pipelines offline since everything is container-based.

**Comment by svettwer** [comment]
Maybe GitHub actions?

**Comment by cliffle** [comment]
### Monthly cost
|   | Github Actions | Appveyor |
|---|:---:|:---:|
| Public Repos | Free | Free |
| Private Repos | $4 per user/month for 3,000min (Team)<br>$21 per user/month for 50,000min (Enterprise)<br>I think we used ~1,200min last month | $29/month for 1 private repository (Basic Plan)<br>$59/month for unlimited repositories (Pro Plan)<br>$99/month for unlimited repositories (Premium Plan)  |

### Plattform support
|   | Github Actions | Appveyor |
|---|:---:|:---:|
| Linux | :heavy_check_mark:<br>Ubuntu 16.04, 18.04, 20.04 | :heavy_check_mark:<br>Ubuntu 16.04, 18.04, 20.04  |
| MacOs | :heavy_check_mark:<br>Catalina 10.15, Big Sur 11.0 | :heavy_check_mark:<br> 10.15 “Catalina”, 10.14 “Mojave” |
| Windows | :heavy_check_mark:<br>Windows Server 2019 | :heavy_check_mark:<br>Visual Studio 2013, 2015, 2017, 2019 |

### Technical capabilities (matrix builds etc.)
|   | Github Actions | Appveyor |
|---|:---:|:---:|
| Matrix Builds | :heavy_check_mark:<br>[see here](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategy) | :heavy_check_mark:<br>[see here](https://www.appveyor.com/docs/build-configuration/#build-matrix) |
| Concurrent Builds | :heavy_check_mark:<br>40 (max 5 macOs) total concurrent jobs for Pro plan<br>60 (max 5 macOs) total concurrent jobs for Team plan<br>180 (max 50 macOs) total concurrent jobs for Enterprise Plan<br>[see here](https://docs.github.com/en/free-pro-team@latest/actions/reference/usage-limits-billing-and-administration#usage-limits) | :heavy_check_mark:<br>1 concurrent build for Basic/Pro plan<br>2 concurrent builds for Premium plan<br>$50/month for additional concurrent job |
| sonar-cloud integration | possible with a [marketplace action](https://github.com/marketplace/actions/sonar-scanner) | seems like you have manually set it up |

**Comment by svettwer** [comment]
Nice overview :+1: 
Would it be possible for you to set up another overview showing the estimated costs for all relevant providers (Travis, GitHub Actions, Appveyor), so that we can compare them? I know this will not be 100% correct but it'll indicate the cost progression. Please put the mentioned comparison into confluence. 

Good job! :rocket:

**Comment by cliffle** [comment]
You can see the cost comparison [here](https://confluence.consol.de/x/F4DcEQ)

**Comment by svettwer** [comment]
Good job!
