### ISSUE TITLE
Improve Syntax error logging

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#341]
As a Sakuli User, I want to obtain more information about a Syntax error, to be able to fix my test more quickly.

Acceptance criteria
- [x] The location of the syntax error is logged (line/row)
- [x] An indicator of the syntax error (missing braces etc.)

**Comment by ZNicoZ** [comment]
Further requirement specification necessary.

**Comment by svettwer** [comment]
Which part is unclear? Maybe I can provide more details.

**Comment by s1hofmann** [comment]
I played around with rollup yesterday evening. 

Syntax errors like superfluous braces are detected during bundling and the error object holds info about the file, line, column and even a little frame snippet which highlights the error.

Things like assignments to `const` values are not detected, these errors are thrown when executing the script. It would require some additional work, but we could make use the source map generated by rollup to enhance these stacktraces
