### ISSUE TITLE
Waiting for stable page can cause _wait calls to be endless 

### ISSUE THREAD

**Issue by tnobody** [sakuli/sakuli#352]
As a Test-Engineer I don't want an "instable" page* to cause a deadlock when using `_wait` with a condition.

**Version**
2.2.1-next.10

**Short overview**
Before an element is fetched Sakuli polls the page source until it is not changing. When using something like `await _wait(2000, () => _isVisible(someElement))` it seems that the wait will never resolve.

**Detailed error description**

I'll create a test case to reproduce this behavior asap

**Comment by tnobody** [comment]
The following testcase was intended to reproduce the behavior described in this issue. It turns out, that it doesn't but gives other interesting findings and misbehavior: 
```typescript
(async () => {
    const testCase: TestCase = new TestCase("I'm still waiting for you");
    try {
        await _navigateTo(`data:text/html;base64;charset=UTF-8, ${Buffer.from(`
            <!doctype html>
            <html>
                <body>
                    <h1 id="heading-under-test">Fetch me</h1>
                    <div id="time"></div>
                    <script>
                        setTimeout(() => {
                            document.getElementById('heading-under-test').innerHTML = 'Fetch me if you can';
                        }, 1000)
                        setInterval(() => {
                            document.getElementById('time').innerHTML = Date.now(); // #1
                        }, 5)
                    </script>
                </body>
            </html>
        `).toString('base64')}`);
        await _wait(5000, () => _isVisible(_heading1(/Fetch me if you can/))) // #2
        // await _wait(2000) //#3
        await _highlight(_heading1(/Fetch me if you can/))
        testCase.endOfStep("started");
    } catch (e) {
        testCase.handleException(e);
    } finally {
        testCase.saveResult();
    }
})().then(done);
```

When you just run this testcase as it is, it will fail with:
```bash
Failed to perform step started:

Error: A non StaleElementReferenceError is thrown during retrying;  
Action timed out after 5000
```

The expected behavior would be that the element became visible at least after 1s+ and the `_wait` timeout would resolve.

If we comment out #<span />2 instead of #<span />3 test will run successfully as expected.

When we comment out #<span/>1 (which leads to a stable dom) both scenarios will run successfully

**Comment by s1hofmann** [comment]
Should be obsolete with #355

**Comment by ZNicoZ** [comment]
test before close

**Comment by cliffle** [comment]
I just tested it with #355 and the `_wait` timeout resolves as expected.
