### ISSUE TITLE
Update TypeScript version

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#362]
As a Sakuli developer I want to be able to use a recent version of TypeScript (e.g. 3.8) which comes with new language features.

**Comment by cliffle** [comment]
The update to typescipt 3.8.3 breaks our build because of a [breaking change](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#local-and-imported-type-declarations-now-conflict) in typescript 3.7, which is used in `command-module-provider.interface.ts`.
