### ISSUE TITLE
False node version in documentation. Sakuli `2.3.x` is not yet ready for node `12.x` due to outdated dependency

### ISSUE THREAD

**Issue by progaddict** [sakuli/sakuli#368]
**Version**
```
> node --version && npm --version 
    v12.16.1
    6.13.4
> grep '@sakuli/cli' package.json 
    "@sakuli/cli": "^2.2.0"
> uname -svorip
    Linux 5.3.0-40-generic #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020 x86_64 x86_64 GNU/Linux
```

**Short overview**
[Documentation](https://sakuli.io/docs/getting-started/prerequisites/) says:
> Starting with version 2.3.0, Sakuli also supports v12.x (lts/erbium).

However, when installing Sakuli `^2.2.0` on node `v12.16.1` the installation of `opencv4nodejs-prebuilt@4.15.2` fails due to node-gyp compilation errors.

**Detailed error description**
There are compilation errors like the following one below:
```
../cc/macros.h:7:76: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
    7 | #define FF_NEW_INSTANCE(ctor) Nan::NewInstance(Nan::New(ctor)->GetFunction()).ToLocalChecked()
```

Sakuli `^2.2.0` has the following dependency: https://github.com/nut-tree/opencv4nodejs/releases/tag/v4.15.2

This dependency contains precompiled OpenCV for `node-v67-linux-x64` "platform" which corresponds to node `10.x` and not to node `12.x`. This fact results in OpenCV to be recompiled by `node-gyp` when installed on node `12.x`. The recompilation fails of course because `12.x` has different API than the `10.x` version.

**Steps to reproduce error**
```
> sudo apt-get install -y build-essential python libxtst-dev libpng++-dev
> nvm use 12.16.1 # or: nvm install --lts
> cd "$(mktemp -d)"
> npm init # init the project
> npm i @sakuli/cli
```

**Additional content**
Please update Sakuli to use `opencv4nodejs-prebuilt@5.3.0` which should be compatible with node `12.x` **OR** update the documentation by stating that node `10.x` should be used.

Related: https://github.com/sakuli/sakuli/issues/266

Workaround: use node `10.x` instead of `12.x`.

**Comment by s1hofmann** [comment]
As stated in docs, Sakuli v2.2.0 does not support node v12.x.

If you want to use Sakuli with node v12.x, please install Sakuli v2.3.0 or later.
