### ISSUE TITLE
Feature: Resume web driver session OR Alternative feature: Sakuli interactive mode

### ISSUE THREAD

**Issue by progaddict** [sakuli/sakuli#374]
**Short overview**
As a Sakuli user, who writes relative long use cases, I'd like to have an ability to start the test case not from the beginning but from the last successful step.

_Alternative feature:_ as a Sakuli user I'd like to have a REPL shell similar to node's REPL where I could input Sakuli commands interactively.

**Use case**
I need to write a test case which consists of a 100 small steps like <code>await _click(_button('Login'));</code>

It is frustrating when the test case fails because of e.g. an incorrect XPath selector or a timeout.

It would be nice if the test case could be resumed from the last successful step **OR** if Sakuli would have a REPL (i.e. interactive) mode with a long lived web driver session.

**Detailed feature description**
See **Use case**.

**Additional content**
None

**Comment by svettwer** [comment]
Hiho :wave: 
Sorry for the late response. I feel your pain at this point. We have a Sakuli recorder on the list where you get the possibility to record the actions you perform in the browser and export a test script reflecting your steps. I think this might help you out. An interactive shell would be a good extension for that recorder.

Resuming a test case at the last successful step is a good idea but incredible hard to realize from my current point of view. As Sakuli just uses a third party system as a user would do, reconstructing a certain state in the test case is heavily dependent on the system we are working with. From my perspective, this is nothing we could ship as a feature and expect it to work reliably on every user system.

**Comment by svettwer** [comment]
I'll close this issue as I've moved the idea of an interactive shell into the Sakuli recorder namespace. As the namespace is not public, it is unfortunately not possible for you to follow the progress of that feature. 
Thanks a lot for your input! :tada:
