### ISSUE TITLE
Inconsistent logging behavior on log.level=debug

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#376]
As a Sakuli user, I want to obtain all log messages for debug level (error, warning, info, debug), when I set the log level to debug in the config, so that I receive all important information for my debugging analysis.

**Acceptance criteria**
- [ ] All messages for the respective log level are written to the log file

*Additional acceptance criteria from https://github.com/sakuli/sakuli/issues/376#issuecomment-684507496*:
- [ ] fix forwarder error logging

**Additional information**
When `log.level=debug` is set in `testsuite.properties`, the log does not contain all Info messages anymore.
Log with `log.level=info`:
```
[Wed Mar 11 2020 16:29:37 GMT+0100 (GMT+01:00)] INFO: Started Execution
[Wed Mar 11 2020 16:29:38 GMT+0100 (GMT+01:00)] INFO: Start Testcase Testcase
[Wed Mar 11 2020 16:29:39 GMT+0100 (GMT+01:00)] INFO: Finish action navigateTo successfully after 0.793s
[Wed Mar 11 2020 16:29:41 GMT+0100 (GMT+01:00)] INFO: Finish action highlight successfully after 2.148s
[Wed Mar 11 2020 16:29:41 GMT+0100 (GMT+01:00)] INFO: Finish action click successfully after 0.047s
[Wed Mar 11 2020 16:29:43 GMT+0100 (GMT+01:00)] INFO: Finish action highlight successfully after 2.081s
[Wed Mar 11 2020 16:29:43 GMT+0100 (GMT+01:00)] INFO: Finish action click successfully after 0.054s
[Wed Mar 11 2020 16:29:44 GMT+0100 (GMT+01:00)] INFO: Finished Execution
```

Log with `log.level=debug`:
```
[Wed Mar 11 2020 16:30:17 GMT+0100 (GMT+01:00)] INFO: Started Execution
[Wed Mar 11 2020 16:30:18 GMT+0100 (GMT+01:00)] INFO: Start Testcase Testcase
[Wed Mar 11 2020 16:30:18 GMT+0100 (GMT+01:00)] DEBUG: Start action navigateTo
[Wed Mar 11 2020 16:30:19 GMT+0100 (GMT+01:00)] INFO: Finish action navigateTo successfully after 0.896s
[Wed Mar 11 2020 16:30:19 GMT+0100 (GMT+01:00)] DEBUG: Start action highlight
[Wed Mar 11 2020 16:30:21 GMT+0100 (GMT+01:00)] INFO: Finish action highlight successfully after 2.154s
[Wed Mar 11 2020 16:30:21 GMT+0100 (GMT+01:00)] DEBUG: Start action click
[Wed Mar 11 2020 16:30:21 GMT+0100 (GMT+01:00)] INFO: Finish action click successfully after 0.044s
[Wed Mar 11 2020 16:30:21 GMT+0100 (GMT+01:00)] DEBUG: Start action highlight
[Wed Mar 11 2020 16:30:23 GMT+0100 (GMT+01:00)] INFO: Finish action highlight successfully after 2.089s
[Wed Mar 11 2020 16:30:23 GMT+0100 (GMT+01:00)] DEBUG: Start action click
[Wed Mar 11 2020 16:30:23 GMT+0100 (GMT+01:00)] INFO: Finish action click successfully after 0.042s
[Wed Mar 11 2020 16:30:24 GMT+0100 (GMT+01:00)] DEBUG: Closed webdriver
```

`INFO: Finished Execution` is missing completely. In addition, when the prometheus forwarder throws an error during gauge creation, the error is also not displayed in the logs. Neither on `log.level=debug` or `log.level=info`. I assume we have a race condition in the logging.

**Comment by svettwer** [comment]
Since we mostly wrote the loggers ourselves, I would consider in this context whether we should not simply use a lib. This makes the code base smaller and reduces our responsibilities.

**Comment by svettwer** [comment]
I think I found the race condition : https://github.com/sakuli/sakuli/blob/21103ed39efb521372e985c1eebe9eaefde841a0/packages/sakuli-commons/src/logger/simple-logger.class.ts#L21-L25

**Comment by svettwer** [comment]
Does not occur on master anymore

**Comment by svettwer** [comment]
It is back again!

**Comment by svettwer** [comment]
As we had more issues with the current logger implementation I suggest to consider a change to winston.js to handle logging concerns.

**Comment by cliffle** [comment]
The race condition actually happens here:
https://github.com/sakuli/sakuli/blob/c19fb226daca89300d2035e4b95aeb105618b462/packages/sakuli-cli/src/commands/run-command.function.ts#L89-L96

Node terminates Sakuli before the logger has the chance to write all log messages to the file. This also results in never reaching code (e.g. `invokeIfPresent(cleanLogConsumer);`) after `process.exit()` is called.

[The official documentation on process.exit](https://nodejs.org/docs/latest-v12.x/api/process.html#process_process_exit_code) shows that we misuse the function with our current implementation. Instead, we should use `process.exitCode` to terminate Sakuli gracefully after all log messages have been written. This also solves the issue that `cleanLogConsumer` is never been called.


Other things I found during the refinement somewhat related to this issue:
- The log output for an error in the Prometheus forwarder looks currently like this:
```
ERROR: There were errors during forwarding: {}
```
Using `e.message || e` fixes the issue.
https://github.com/sakuli/sakuli/blob/c19fb226daca89300d2035e4b95aeb105618b462/packages/sakuli-core/src/forwarder/connect-forwarder-to-test-execution-context.function.ts#L61-L64

- The type import for WritableStream is somewhat wrong, as an [fs.writableStream is returned](https://nodejs.org/docs/latest-v12.x/api/fs.html#fs_fs_createwritestream_path_options). But this extends from `WritableStream` of Stream/Node so :man_shrugging: 
https://github.com/sakuli/sakuli/blob/c19fb226daca89300d2035e4b95aeb105618b462/packages/sakuli-commons/src/logger/consumer/create-write-stream-consumer.function.ts#L4

**Comment by svettwer** [comment]
We won't change the `NodeJS.WritableStream` to an `fs` import as this would limit the implementation to file system interaction only.
