### ISSUE TITLE
getEnv returns a Promise instead of a value of the requested environment variable

### ISSUE THREAD

**Issue by progaddict** [sakuli/sakuli#377]
**Please give a Sakuli developer a sync way of reading environment variables like `process.env.SOME_URL` in node**

**Version**
2.3.0

**Short overview**
The `Environment` TS interface has the following API:
```typescript
getEnv(key: string): string | null;
```
However the implementation gives a `Promise` back.

**Detailed error description**
The implementation in `sakuli-environment.class.ts` delegates to `runAsAction` from `action.function.ts` which is an async function i.e. it returns a `Promise` (at least for the `getEnv` case).

**Steps to reproduce error**
```typescript
const url = new Environment().getEnv('SOME_URL');
await _navigate(url);
```
Error:
```
TypeError [ERR_INVALID_URL]: Invalid URL: [object Promise]
```

**Additional content**
None

**Comment by s1hofmann** [comment]
Sakuli injects [thenable classes](https://sakuli.io/docs/writing_tests/#thenable-classes) into the testcontext. This way it's possible to provide a fluent async API, but it also results in `Promise` based APIs. See [ThenableEnvironment](https://sakuli.io/apidoc/sakuli-legacy/interfaces/thenableenvironment.html) for reference, which provides the correct signature.
