### ISSUE TITLE
Enhancement: record all `keyDown` actions and if a test gets interrupted (e.g. because of error) do a "cleanup" by invoking `keyUp` for the recorded keys

### ISSUE THREAD

**Issue by progaddict** [sakuli/sakuli#379]
**Short overview**
* There are 2 tests in a suite: A and B.
* Test A has a sequence of keyboard actions:
```javascript
const env = new Environment();
await env.keyDown(Key.CTRL, Key.T);
throw new Error('simulate unhandled error between keyDown and keyUp');
await env.keyUp(Key.CTRL, Key.T);
```
* As a result, CTRL-T combination gets "stuck" after the test ends with an error.
* When test B starts after test A, suddenly over 9000 new browser tabs get opened because the CTRL-T keys are still active (i.e. pressed).
* Current workaround:
```javascript
const env = new Environment();
try {
  await env.keyDown(Key.CTRL, Key.T);
} finally {
  await env.keyUp(Key.CTRL, Key.T);
}
```
* It would be nice if Sakuli could do a cleanup of such "forgotten" keys automatically after each test even if the test ends up with success (in which case a warning could be logged that e.g. keys X,Y, Z were not cleared by the test).

**Use case**
See above.

**Detailed description**
See above.

**Additional content**
TBD

**Comment by progaddict** [comment]
I'll write an example test suite a little bit later

**Comment by svettwer** [comment]
Steps to reconstruct:

```typescript
(async () => {
  const testCase = new TestCase("Shift-S***");
  const env = new Environment();
  try {
    await env.keyDown(Key.SHIFT);
    throw Error("foo!")
    await env.keyUp(Key.SHIFT);
  } catch (e) {
    await testCase.handleException(e);
  } finally {
    await testCase.saveResult();
  }
})();
```

1. Execute the test
2. Type something somewhere without touching your shift key
3. See the capital letters flow

**Comment by svettwer** [comment]
criteri di accettazione:
- [ ] keyboard buttons are released on error
- [ ] mouse buttons are released on error

**Comment by svettwer** [comment]
Dev Hint: `ButtonRegistry` in `sakuli-legacy`

**Comment by svettwer** [comment]
-[ ] Region.keydown
-[ ] ThenableRegion.keydown
-[ ] Environment.keydown
-[ ] ThenableEnvironment.keydown
-[ ] KeyboardActionsApi.keydown
-[ ] ActionApi.keydown
-[ ] SahiApi.keydown
-[ ] LegacyApi.keydown

-[ ] Region.keyup
-[ ] ThenableRegion.keyup
-[ ] Environment.keyup
-[ ] ThenableEnvironment.keyup
-[ ] KeyboardActionsApi.keyup
-[ ] ActionApi.keyup
-[ ] SahiApi.keyup
-[ ] LegacyApi.keyup

-[ ] Region.mouseDown
-[ ] ThenableRegion.mouseDown
-[ ] MouseActionApi.mouseDown
-[ ] ActionApi.mouseDown
-[ ] SahiApi.mouseDown
-[ ] LegacyApi.mouseDown

-[ ] Region.mouseUp
-[ ] ThenableRegion.mouseUp
-[ ] MouseActionApi.mouseUp
-[ ] ActionApi.mouseUp
-[ ] SahiApi.mouseUp
-[ ] LegacyApi.mouseUp

**Comment by svettwer** [comment]
Hi @progaddict!

The implementation has been done and is now available as tech preview under `@sakuli/cli@next`
