### ISSUE TITLE
Ship typings with @sakuli/core

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#388]
@s1hofmann commented on [Thu Mar 19 2020](https://github.com/sakuli/sakuli-demos/issues/8)

During release v2.3.0 we noticed that after running an audit, TypeScript complained about missing type infos for `yargs`. Running the audit updated several transitive dependencies, which seemed to provide these typings.

We did not notice this fact until said audit, which broke our build. As a workaround, we added `@types/yargs` as a devDependecy to our forwarder packages, but we should address this issue by shipping typings as dependency with `@sakuli/core'.

**Comment by cliffle** [comment]
This was already addressed in https://github.com/sakuli/sakuli/commit/d18eb5b4f4a9b5e52a694ded46423f1d0dfd819f and https://github.com/sakuli/sakuli-enterprise-forwarder/commit/d2673176ee6451d696a1db867745cb6bac4d9ff6
