### ISSUE TITLE
nut.js: getRegionFromFocusedWindow(); returns whole display

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#390]
@ZNicoZ commented on [Tue Feb 18 2020](https://github.com/sakuli/todo/issues/106)

At the moment getRegionFromFocusedWindow(); returns a region of the whole display. This was implemented due to legacy reasons and as there is no ready-to-go cross plattform way to receive a region from a window.

@s1hofmann already started on a fix in Nov. 2019 but it never got prioritized.
https://github.com/nut-tree/nut.js/issues/5

In my opinion this is an important feature and should be working.

**Comment by svettwer** [comment]
@ZNicoZ decided to work on it without estimation

**Comment by s1hofmann** [comment]
Fist PR concerning implementation in libnut: https://github.com/nut-tree/libnut/pull/23
