### ISSUE TITLE
_count does not work

### ISSUE THREAD

**Issue by progaddict** [sakuli/sakuli#394]
**Version**
```
 > node --version && npm --version
v12.16.1
6.13.4
> grep '"@sakuli/cli"' package.json
    "@sakuli/cli": "^2.3.0",
```

**Short overview**
`_count` returns 1 instead of 3

**Detailed error description**
see https://github.com/sakuli/sakuli/pull/393

**Steps to reproduce error**
see https://github.com/sakuli/sakuli/pull/393

**Additional content**
see https://github.com/sakuli/sakuli/pull/393

**Comment by svettwer** [comment]
Hi :wave: 
`_count` works as designed. Unfortunately the signature is not intuitive but this is something we migrated from Sakuli 1. So for now, we have to deal with it.

Your test can be fixed if you count like this:
`await _count('_link', "a-breadcrumb__link");`
so line 32 should be 
`const breadcrumbsCount2 = await _count('_link', "a-breadcrumb__link");`

BR
Sven

**Comment by s1hofmann** [comment]
Closed due to inactivity.
