### ISSUE TITLE
_leftOf/_rightOf only usable in tables

### ISSUE THREAD

**Issue by cliffle** [sakuli/sakuli#397]
**Version**
2.3.0

**Short overview**
As a Sakuli User, I want to be able to use `_leftOf`/`_rightOf`/`_leftOrRightOf` outside of tables to find elements.

**Detailed error description**
Due to compatibility to Sakuli 1, `_leftOf`/`_rightOf`/`_leftOrRightOf` can only be used within a table. This is very limiting. Instead it should implemented simliar to `_above`/`_under`, which uses the position in the viewport to determine the relation.

**Steps to reproduce error**
```typescript
(async () => {
    const testCase = new TestCase();
    try {
        await _navigateTo("https://sakuli.io/docs/getting-started/");
        await _highlight(_video(0));
        await _highlight(_link(0, _rightOf(_video(0))));
        await _highlight(_link(0, _leftOf(_video(0))));
        await _highlight(_link(0, _leftOrRightOf(_video(0))));
    } catch (e) {
        await testCase.handleException(e);
    } finally {
        await testCase.saveResult();
    }
})();
```

**Comment by svettwer** [comment]
As the display of an element is heavily CSS dependent, how would you implement that as the rendering is not inferrable by the DOM?

**Comment by cliffle** [comment]
`_above`, `_under` and `_underOrAbove` determine the relations via the position of the two elements implemented in [edges.function.ts](https://github.com/sakuli/sakuli/blob/2fda9a30071f7d2a853733b94899f4662f9cf45c/packages/sakuli-legacy/src/context/sahi/relations/edges.function.ts#L109)
I suggest implementing it the same way.

**Comment by svettwer** [comment]
Ah, okay. You want to reuse the vector calculation that is already present. :bulb:
