### ISSUE TITLE
file uploads not found

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#400]
As a Sakuli user, I want to upload a file to test my current use case but it is not found by the `_file` accessor.

**Additional information**
```html
<html>
  <body>
    <input type="file" id="fileUpload"/>
  </body>
</html>
```

```javascript
(async () => {
    const testCase = new TestCase();
    const url = "file:///home/foobar/sample/foo.html";
    try {
        await _navigateTo(url);
        await _click(_file("fileUpload"));
    } catch (e) {
        await testCase.handleException(e);
    } finally {
        await testCase.saveResult();
    }
})();
```

```
[Mon Mar 30 2020 12:17:40 GMT+0200 (GMT+02:00)] ERROR: Error in testcase Container Run: invalid argument
  (Session info: chrome=80.0.3987.149)
InvalidArgumentError: invalid argument
  (Session info: chrome=80.0.3987.149)
    at Object.throwDecodedError (/home/foobar/IdeaProjects/container_bootstrap/node_modules/selenium-webdriver/lib/error.js:550:15)
    at parseHttpResponse (/home/foobar/IdeaProjects/container_bootstrap/node_modules/selenium-webdriver/lib/http.js:560:13)
    at Executor.execute (/home/foobar/IdeaProjects/container_bootstrap/node_modules/selenium-webdriver/lib/http.js:486:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Acceptance criteria**
- [ ] file uploads can be clicked so that an open file dialog pops up.

**Comment by tnobody** [comment]
Two thoughts on this:
- I agree, that your demo code should not throw an Error
- I'm curious if it is intended to open the popup which would cause the user to switch to native functionality (creating screenshots etc) just to set the value of a textbox (which it is at least)
- I found that Sahi provided [such a functionality](https://sahipro.com/docs/sahi-apis/action-apis.html#File%20Upload) unfortunately I couldn't find in Sakuli DSL :/ would be better approach to me rather than native interaction where it's seldom necessary.

**Comment by tnobody** [comment]
I had another finding on this:

It seems to be the webdriver which doesn't work as expected here

Running this test
```typescript
it("should run", async () => {
    await driver.get(
      mockHtml(`
        <html>
          <body>
            <input type="file" id="fileUpload"/>
          </body>
        </html>
        `)
    );

    await driver.findElement(By.css("#fileUpload")).click();

    await new Promise(res => setTimeout(res, 5000));
  });
```

Will also fail with:

```bash
FAIL  ./run.spec.ts
  test
    ✕ should run (1089ms)

  ● test › should run

    InvalidArgumentError: invalid argument
      (Session info: chrome=80.0.3987.149)

      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:542:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:468:26)

```

With `"chromedriver": "^80.0.1"`

Removing the invocation of `click` let the test pass.

**Comment by svettwer** [comment]
I managed to handle file uploads by this article on stackoverflow.
https://stackoverflow.com/questions/11256732/how-to-handle-windows-file-upload-using-selenium-webdriver
