### ISSUE TITLE
create-project-command: Add default preset

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#403]
As a Sakuli user, I want the `create-project` command to add `@sakuli/legacy` as default preset.

Currently, the `create-project` command does not add a preset, which defaults to `@sakuli/legacy` implicitly.
When using `create-project` in conjunction with e.g. `enable-enterprise`, this missing preset causes runtime errors when e.g. working with properties.

Acc. crit.:

- [ ] `package.json` of created project contains the `@sakuli/legacy` preset

**Comment by svettwer** [comment]
Still required with preset auto discovery?

**Comment by svettwer** [comment]
Solved by #276
