### ISSUE TITLE
enable-enterprise: Check for @sakuli/legacy preset

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#404]
As a Sakuli user, I want the `enable-enterprise` command to add required presets if not present.

E.g. when running `enable-enterprise` on a testsuite which does not explicitly list the `@sakuli/legacy` preset in its `package.json`, `enable-enterprise` should make up for this case.
Not adding the `@sakuli/legacy` preset will break working suites, since it will no longer be used implicitly.

Acc. crit.:

- [ ] Testsuites with existing legacy preset will not be affected
- [ ] Testsuites with missing legacy preset will have it configured afterwards

**Comment by tnobody** [comment]
Also consider #276 as an alternative solution (might be more effort but would make this issue unnecessary)

**Comment by svettwer** [comment]
Same thought as for #403 Still required after solving #276

**Comment by svettwer** [comment]
solved by #276
