### ISSUE TITLE
Improve image recognition capabilities

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#406]
This issue relates to #327.

When taking screenshots from the desktop to be used in a test case that is executed in a container or on a remote test machine, the image recognition most likely fails, even if the OS and resolution is the same during screenshot creation and test execution. In general the image recognition does not "feel stable and reliable". We should improve this as this is a unique selling point of Sakuli.

Acceptance criteria:
- [ ] Screenshots from my desktop with same resolution are reliably found when test is executed in a container
- [ ] Screenshots from my desktop with same resolution are reliably found when test is executed on a remote machine (e.g. VM)

**Comment by s1hofmann** [comment]
As discussed today our general opinion was that such tasks should be carried out in a wider scope of future uses.
