### ISSUE TITLE
Error screenshots are much smaller than takeScreenshot screenshots

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#408]
As a sakuli user, I want the takeScreenshot screenshots taken via the environment are just as small as the error screenshots created in case of a test case failure. Currently the difference is some KB vs some MB

**Acceptance criteria**
- [ ] the screenshots created via `env.takeScreenshot()` are reduced in size to some hundred KB instead of some MB.

**Comment by s1hofmann** [comment]
@svettwer Could you provide some samples? I'm not able to reproduce described behaviour.

**Comment by svettwer** [comment]
Unfortunately not. Got this report from a user.
I'll ask for more information

**Comment by svettwer** [comment]
closed due to missing information from user.
