### ISSUE TITLE
Sakuli container fails to start in K8S but works locally in docker

### ISSUE THREAD

**Issue by progaddict** [sakuli/sakuli#417]
**Version**

* sakuli image: 2.3.0
* local docker:
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:55 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:26 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
* kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Short overview**

Sakuli container fails to start in K8S but works locally in docker.

**Detailed error description**

When I start Sakuli container locally via docker (see https://github.com/progaddict/sakuli/blob/vnc-resolution-env-var-causes-sakuli-to-crash/packages/e2e/docker.e2e-sakuli-tests.sh) it works as expected.

However when I deploy the same Sakuli image to K8S (see https://github.com/progaddict/sakuli/blob/vnc-resolution-env-var-causes-sakuli-to-crash/packages/e2e/k8s.e2e-sakuli-tests.yml), the container fails to start and log (stdout) shows the following error:
```
sh: 1: /headless/.vnc/xstartup: Permission denied
```

Full K8S stdout: https://github.com/progaddict/sakuli/blob/vnc-resolution-env-var-causes-sakuli-to-crash/packages/e2e/e2e-sakuli-tests.k8slog

**Steps to reproduce error**

see https://github.com/sakuli/sakuli/pull/416 or PM me

**Additional content**

In both cases (local docker and K8S) Sakuli detects the same user and group IDs:
```
USER_ID: 1000, GROUP_ID: 0
```

**Comment by svettwer** [comment]
It seems, this relates to https://github.com/kubernetes/enhancements/issues/213 which states that it is currently not possible to set the Group ID explicitly.

We'll have a look into this and try to find a solution that works for docker and k8s. As group ID 0 is a critical value when writing to volumes on the host system, it is not possible to change the containers group ID back to 0 by default.

**Comment by progaddict** [comment]
hi @svettwer 

Thank you for looking into the issue.

I have an update. I've managed to run Sakuli container in K8S under UID 1000 and GID 1000 (via `securityContext`): https://github.com/progaddict/sakuli/blob/vnc-resolution-env-var-causes-sakuli-to-crash/packages/e2e/k8s.e2e-sakuli-tests.yml#L34

Logs (stdout of the container) confirm that: https://github.com/progaddict/sakuli/blob/vnc-resolution-env-var-causes-sakuli-to-crash/packages/e2e/e2e-sakuli-tests.k8slog#L10

However, Sakuli still unfortunately does not want to run in K8S.

**Comment by svettwer** [comment]
In this case we'd have to test it on k8s ourselves. May take a while to get there. I'm a little curious why the referenced k8s issue is still open of it is possible to start a container with a specific UID. Maybe I missed something?!

**Comment by svettwer** [comment]
Acc crit:
- [ ] try to reconstruct issue
- [ ] root cause analysis

**Comment by svettwer** [comment]
Hi @progaddict :wave: 
I tried to reconstruct the issue. I used a minikube instance and created a image pull secret as described in [S2I Setup](https://sakuli.io/docs/enterprise_features/s2i/#setup), because this also works for k8s. After that, I started the pod like this:

```yml
apiVersion: v1
kind: Pod
metadata:
    name: sakuli
spec:
  containers:
    - name: sakuli
      image: taconsol/sakuli:2.3.0
      env:
        - name: SAKULI_LICENSE_KEY
          value: "LINCEEEEENSE!!!!"
  imagePullSecrets:
    - name: dockerhub-sakuli-secret

```

The container was able to start without any problems
```
[sven@arch1337]: ~/tmp>$ kubectl logs sakuli    
USER_ID: 1000, GROUP_ID: 0
nss_wrapper location: /usr/lib/libnss_wrapper.so


------------------ IMPORT CERTIFICATES    ---------------------------
NO CERTIFICATES PATH FOR IMPORT SET, SKIPPING


------------------ START SAKULI CONTAINER ---------------------------
USER_ID: 1000, GROUP_ID: 0
nss_wrapper location: /usr/lib/libnss_wrapper.so

------------------ update chromium-browser.init ------------------

... set window size 1280 x 1024 as chrome window size!


------------------ change VNC password  ------------------

------------------ start noVNC  ----------------------------

------------------ start VNC server ------------------------
remove old vnc locks to be a reattachable container
start vncserver with param: VNC_COL_DEPTH=24, VNC_RESOLUTION=1280x1024
...
start window manager
...


------------------ VNC environment started ------------------

VNCSERVER started on DISPLAY= :1 
	=> connect via VNC viewer with 172.18.0.4:5901

noVNC HTML client started:
	=> connect via http://172.18.0.4:6901/?password=...



------------------ EXECUTE COMMAND ------------------
Executing command: 'npm --prefix /headless/demo_testcase test'

> sakuli_demo@1.0.0 test /headless/demo_testcase
> sakuli run ./suite

  ____            _              _   _ 
 / ___|    __ _  | | __  _   _  | | (_)
 \___ \   / _` | | |/ / | | | | | | | |
  ___) | | (_| | |   <  | |_| | | | | |
 |____/   \__,_| |_|\_\  \__,_| |_| |_|
                                       
========================================

Initialized Sakuli with 2 Testcases

Writing logs to: suite/_logs/sakuli.log
Started execution
→ Started Testsuite demo_case
  → Started Testcase sakuli.io
   ✓ Finished Step Open Landing Page with state Ok............................................................................................................................1.255s
   ⚠ Finished Step UNNAMED with state Error...................................................................................................................................6.365s
  ⚠ Finished Testcase sakuli.io with state Error..............................................................................................................................7.622s
  → Started Testcase calculator
   → Started Step UNNAMED
```
Okay, the test failed, but this is due to a website change on the demo system. :sweat_smile:

For me, it looks like the container runs fine on k8s. Maybe something in your specific setup is messing up some permission?

**Comment by progaddict** [comment]
Hi @svettwer 

Thanks a lot for looking into this issue.

Well, maybe it has something to do with the AWS flavor of K8S (the EKS). I think for now the issue can be "paused". We can just use the "old" Sakuli image (2.1.0) which works in EKS. Later, when the problem is a blocker, it can be investigated further.

Once again thank you for your time!

**Comment by svettwer** [comment]
Okay, I agree that this might be a side effect of some K8S config we are currently not aware about.
It's nevertheless a little bit unsatisfying to pause it for now. I'd really like to help you solving it. =(
