### ISSUE TITLE
Merge coverage data of test and test:it

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#419]
As a Sakuli developer I want to have a detailed test coverage info.

Currently sonar scanner is run before `test:it` tests, so it doesn't pick up coverage reports generated by these integration tests.
We should change the ordering to also include coverage data from integration tests.

Acc. Crit.:

- [x] `test` and `test:id` are run before sonar scanner on Travis
- [x] Coverage reports are properly merged
- [x] Sonar picks up both `test` and `test:it` coverage info

**Comment by svettwer** [comment]
See https://github.com/nut-tree/nut.js/blob/develop/package.json#L53-L54 as example
