### ISSUE TITLE
Enable fluent API for native actions

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#42]
Hi!

In Sakuli 1 it is possible to state something like 
```javascript
screen.find(imageName).click();
```

Currently Sakuli 2 states for
```javascript
await screen.find(imageName).click();
```

```
(node:14641) [DEP0091] DeprecationWarning: crypto.DEFAULT_ENCODING is deprecated.
× suite test-suite ........................... 3.76s
   × case case screen.find(...).click is not a function
    ✓ step UNNAMED ................................ 3.69s

```

A workaround would be:
```javascript
const image = await screen.find(imageName);
await image.click();
```

Maybe we should alter the legacy API to simplify the migration of testcases to V2.

BR,
Sven

**Comment by tnobody** [comment]
We should investigate in a solution like selenium, where (for example) a WebElement is a Promise and every method which returns a webelement implicitly retruns a promise which resolves to the actual Webelement

**Comment by s1hofmann** [comment]
In my opinion this is not a bug, but an implementation detail.

All native methods are returning `this`, so it's still possible to do method chaining.
The problem with 

```js
await screen.find(imageName).click();
```

is the fact that `find` and `click` are `AsyncFunction`s which return a `Promise<Region>`.
By simply chaining method calls you're effectively trying to call `click()` on a `Promise` object.

```js
await (await screen.find(imageName)).click();
```

would correctly chain both method calls, but doesn't look that nice IMHO.
Another way to express these chained calls would be something like 

```js
await screen.find(imageName).then(target => target.click());
```

For migrations from V1 to V2, these cases need to be taken care of.
Considering the migration command, this should be a separate issue.

**Comment by svettwer** [comment]
Yeah, my point was just the migration from V1 to V2.
You could just remove the bug label and label it differently if you like. =)

**Comment by tnobody** [comment]
I did a little research on this. It seems not easily possible to somehow wrap promises within a fluent API.
I found one approach here: http://blog.minimum.se/2017/07/18/fluent-chained-api-asynchronous-functions-async-methods-Javascript.html
But I think this will lead to a lot of refactoring

Another alternative would be using something like fiber: https://www.npmjs.com/package/fibers

If we agree to let the api as it is right now, we should issue a new feature in migration tool :)

**Comment by s1hofmann** [comment]
Might be possible like: https://github.com/SeleniumHQ/selenium/blob/abf2219b575bea98e4093fb13843f487da7edb51/javascript/node/selenium-webdriver/lib/webdriver.js#L2227
