### ISSUE TITLE
Provide LegacyProps to LegacyAPI

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#420]
As a Sakuli developer I want to make certain behaviour configurable, e.g. timeouts for ongoing network traffic or scroll timeouts.

Currently, the legacy API does not have access to the legacy properties, so there's no way of configuring these values.

**Comment by svettwer** [comment]
Please list all required/desired properties. <3

**Comment by svettwer** [comment]
closed for now. If this becomes important again, please open a new issue.
