### ISSUE TITLE
On Windows: env.type with capital letters leads to hanging shift key

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#430]
As a Sakuli user, I want to type Text like `env.type("ASDF")` without an hanging shift key afterwards. Currently the shift key is pressed all the time after typing so that `TAB` commands are inverted. This is disturbing text execution heavily.

**Comment by svettwer** [comment]
Currently unable to reproduce on my win 10 vm. @s1hofmann thought the issue might be related to the users system config. I'll contact them for more more details.

**Comment by svettwer** [comment]
[sakuli-win-tc.zip](https://github.com/sakuli/sakuli/files/4836096/sakuli-win-tc.zip)
Sample test case for reconstruction. Please remember to change the path to the local `testpage.html` in the test case.

**Comment by s1hofmann** [comment]
Tested both the provided sample and another check using native applications. Working fine on both of my VMs, not problem with switching between upper / lower-case.

**Comment by svettwer** [comment]
related to nut-tree/libnut#12
