### ISSUE TITLE
current @next installation fails on windows

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#431]
As a Sakuli user, I want to test the `@next` builds on my windows test host, to use some features from the tech preview. Currently the installation fails

**Comment by svettwer** [comment]
Currently not reproducible with my local win 10 VM. The user used Win server if I remember correctly. I'll ask them for the machine specs.

**Comment by s1hofmann** [comment]
Did a fresh install of latest `@next` release, runs smoothly.
I'm assuming problems with network access when trying to install OpenCV bindings.

**Comment by svettwer** [comment]
closed as not reproducible
