### ISSUE TITLE
_highlight doesn't "null check" if a rect-object is obtained from element

### ISSUE THREAD

**Issue by tnobody** [sakuli/sakuli#434]
`_highlight` obtains "rect information" from a given `WebElement`. It seems that this method:

https://github.com/sakuli/sakuli/blob/5be44e8c64f916ce5c36f3328db030e8b5104ee8/packages/sakuli-legacy/src/context/sahi/action/common-action/common-actions.function.ts#L52-L52

returns `undefined` in some circumstances [1]. Consequently, the highlighting will fail with an error message like `cannot read property y of undefined`.

Null checking will introduce the question of "what will happen when no rect is obtained". Possible Approaches:

- Do nothing (no highlight, no error, maybe debug logging)
- Throw an explicit Error Message
- Apply the highlight style to the element directly instead of drawing a box based on the element rectangle

[1]: I assume that one circumstance could be that the element actually exists but is not rendered (e.g. `display: none`) a the point of time when sakuli tries to highlight it.

**Comment by svettwer** [comment]
We agreed to the following solution attempt if `getRect()` returns `undefined`:
Draw a highlight to the element itself (e.g. with border)
