### ISSUE TITLE
Test artefact does not get removed

### ISSUE THREAD

**Issue by julianxyz** [sakuli/sakuli#437]
When running the following test:
```shell script
npm run test packages/sakuli-legacy/src/context/common/test-case/test-case.class.spec.ts
```
the following folder, `'${sakuli.log.folder}'` remains in the current working directory.

**Comment by svettwer** [comment]
Could you please provide some more information? Where is the folder created and what is the issue with it? Why would you like to remove the log folder after execution?

**Comment by svettwer** [comment]
Issue seems to be located in `test-case.class.spec.ts`

**Comment by julianxyz** [comment]
The folder seems to be only generated by this test in `packages/sakuli-legacy/src/context/common/test-case/test-case.class.spec.ts` at line `367`:
```typescript
    it("should update last step from cache", async () => {
      (<jest.Mock>testExecutionContext.getCurrentTestCase).mockReturnValue({
        getChildren: () => [TestStep("step-1", 100, 200), TestStep("", 0, 0)],
      });
      await tc.handleException(Error("Dummy"));
      expect(testExecutionContext.updateCurrentTestStep).toHaveBeenCalledWith(
        expect.objectContaining({
          kind: "step",
          id: "step-2",
          warningTime: 100,
          criticalTime: 200,
        })
      );
    });
```
