### ISSUE TITLE
Save screenshot on failing image search 

### ISSUE THREAD

**Issue by julianxyz** [sakuli/sakuli#439]
As a sakuli user, I would like the screenshot of the session where images are matched against to be saved, whenever the image search fails.

Acc. criteria:
- [ ] Save screenshot of failed image search.
- [ ] Mark the closet match of the searched image on the error screenshot with a colored frame.

**Comment by svettwer** [comment]
Sakuli already creates a screenshot for failed image searches but the border would be a great enhancement. :+1:

**Comment by svettwer** [comment]
Sometimes the native highlight is just a solid block. This would not help identifying anything. Maybe this is something to consider in nut.js first.

![image](https://user-images.githubusercontent.com/25754312/97988781-ce3cc880-1ddd-11eb-9501-2c1835d2b24d.png)
