### ISSUE TITLE
Package Releases as executables for easier distribution

### ISSUE THREAD

**Issue by tnobody** [sakuli/sakuli#46]
The packages should be built in closed repos.

As a Enterprise User i want to be able to install Sakuli (with all enterprise features) without using NPM, so that I can use Sakuli even behind enterprise proxy setups or other restrictions.

**Additional Information**

Steps to bundle Sakuli as an installable (cross-platform) application:
- Bundle Sakuli packages together with its Enterprise dependencies (and node runtime) as an executable. [PKG](https://github.com/zeit/pkg) seems to be a approachable tool
- A downloadable executable should be accessible for the User (Github releases, that is accessible with GH-Token?)
- Each release of Sakuli (expect the @next versions) should also produce a new release of the installer

**Comment by s1hofmann** [comment]
Did a few tests today, looks really promising! 👍

**Comment by tnobody** [comment]
@cliffle is there something to review? ;)

**Comment by cliffle** [comment]
Sorry, I forgot to comment that I implemented it in the [sakuli-executable](https://github.com/sakuli/sakuli-executable) repository.

**Comment by tnobody** [comment]
We could point out that the webdriver has to be configured in the path. 
Everything else looks very promising. 
Good Work 👍

**Comment by svettwer** [comment]
follow up issues incoming!
