### ISSUE TITLE
Support for EL-like syntax in Property loader

### ISSUE THREAD

**Issue by tnobody** [sakuli/sakuli#51]
Currently some properties of the legacy package are using values which include Javas Expression Language syntax, to resolve default values.

Example:
```typescript

    /**
     * optional service description forwarded to nagios check result. DEFAULT: testsuite.id
     */
    @Property('sakuli.forwarder.gearman.nagios.service_description')
    nagiosServiceDescription: string = "${testsuite.id}";
```

currently the name of nagiosServiceDescription would be resolved to `"${testsuite.id}"` but it should resolve to the actual value of the property testsuite.id in the current PropertyMap

**Comment by s1hofmann** [comment]
Rescheduled to RC3

**Comment by s1hofmann** [comment]
Rescheduled to v2.0.1
