### ISSUE TITLE
sahiQueryToString not rendering relations properly

### ISSUE THREAD

**Issue by svettwer** [sakuli/sakuli#518]
As a Sakuli user, I expect relations between web elements to be rendered in case of an error, so that I'm able to identify the root cause of the error more efficient.

Acceptance criteria:
- [x] Output log messages when relations are used
- [x] Remove `relations` from in assertion error messages

Additional information:
```
await _navigateTo(https://sakuli.io/e2e-pages/fryed-egg);
await _assertNotContainsText("FRY", _heading1(/LET'S FRY AN EGG/, _in(_byXPath("/html/body"))));
```
results in

```
AssertionError [ERR_ASSERTION]: The following element contains the prohibited text "FRY:"

locator: By(css selector, h1)
identifier: /LET'S FRY AN EGG/
relations:
```

**Comment by cliffle** [comment]
There are a few things I found:

1. With the current implementation the relation of this element will always be empty. After finding the right element with the given relation, the `WebElement` is always going to be converted to a `SahiElementQuery` via `webElementsToQuery` in `relations-api.function.ts`:

https://github.com/sakuli/sakuli/blob/2b820c8da2f5d68b07408a231b5288c82eaf72bb/packages/sakuli-legacy/src/context/sahi/relations/relations-api.function.ts#L35-L41

So we can see that the relation of the returned `SahiElementQuery` is always empty.

After fixing this issue, we can go back to `_assertNotContainsText` or any other assert function and look at how the error message is created.

https://github.com/sakuli/sakuli/blob/2b820c8da2f5d68b07408a231b5288c82eaf72bb/packages/sakuli-legacy/src/context/sahi/assertion/assertion-api.function.ts#L62-L64

https://github.com/sakuli/sakuli/blob/2b820c8da2f5d68b07408a231b5288c82eaf72bb/packages/sakuli-legacy/src/context/sahi/sahi-element-utils.ts#L31-L41

Here comes problem number 2:
We try to get the relation via `f.name` to determine which relation it is. Unfortunately, all the relations return an anonymous function, which results in `f.name` to be an empty string. So we have to change all the current relation implementation to make Function.name work.

I don't think the result justifies all the effort we need to put in. A much simpler solution is to remove the relation from the error message and add log outputs when relations are used. For `_in` it could look like `applying _in with query ... `. The log output would be like this:

```
...
TRACE: 1 Elements found after applying identifier 0
DEBUG: Found 1 Elements for RegEx: /LET'S FRY AN EGG/
DEBUG: applying _in with query By(xpath, /html/body)
TRACE: 1 Elements found after applying relations
DEBUG: Found 1 Elements for RegEx: /.*/
TRACE: 1 Elements found after applying identifier /LET'S FRY AN EGG/
DEBUG: _containsText: Checking text "FRY" with element:
...
```

**Comment by cliffle** [comment]
Updated acceptance criteria based on refinement
