### ISSUE TITLE
Sakuli does not exit when waitForImage fails with high timeout

### ISSUE THREAD

**Issue by cliffle** [sakuli/sakuli#523]
**Short overview**
When using `waitForImage` with higher timeout (>= 4-5 seconds), Sakuli fails to exit but gets stuck after printing the error message.

**Detailed error description**
Probably due to a bug in nut.js, Sakuli cannot exit properly.
* https://github.com/nut-tree/nut.js/issues/173
* https://github.com/nut-tree/nut.js/issues/174

**Steps to reproduce error**
Add a high similarity in the e2e suite before `waitForImage` is used, so that it fails fails.

```typescript
(async () => {
  const testCase = new TestCase("Fry a typed egg");
  const url = "https://sakuli.io/e2e-pages/fryed-egg";
  const screen = new Region();
  const env = new Environment();
  try {
    await _navigateTo(url);
    await _highlight(_heading1(/LET'S FRY AN EGG/), 2000);
    await env.setSimilarity(0.95);
    await screen
      .find("source_egg.png")
      .highlight(1)
      .mouseMove()
      .mouseDown(MouseButton.LEFT);
    await testCase.endOfStep("Search egg");
    await env.setSimilarity(0.6);
    await screen
      .find("target_pan.png")
      .highlight(1)
      .mouseMove()
      .mouseUp(MouseButton.LEFT);
    await testCase.endOfStep("Drop egg");
    await new Region(0, 0, 10, 10).highlight(1).mouseMove();
    await env.setSimilarity(0.99);
    await screen.waitForImage("result.png", 5).highlight(1);
    await testCase.endOfStep("Check result");
  } catch (e) {
    await testCase.handleException(e);
  } finally {
    await testCase.saveResult();
  }
})();
```

**Comment by svettwer** [comment]
Upstream issue

**Comment by svettwer** [comment]
Fixed by https://github.com/nut-tree/nut.js/pull/177

**Comment by svettwer** [comment]
As we've currently `@nut-tree/nut-js@next` in place on development, a dedicated version update is not required after the upstream PR has been merged.

**Comment by svettwer** [comment]
Tested after nut-js build => works as expected
