### ISSUE TITLE
Revisit specification of _near relation

### ISSUE THREAD

**Issue by julianxyz** [sakuli/sakuli#563]
The _near relation ...
https://github.com/sakuli/sakuli/blob/fdb3a6dcf892b65e15a0f49e35eb87027a20bddf/packages/sakuli-legacy/src/context/sahi/relations/relations-api.interface.ts#L7
... is defined a bit unintuitive, if you just go by the name of it.

In this relation elements are ordered by their distance to an anchor element.
The distance between two elements is determined by the minimum amount of steps
you have to move up or down the dom-hierarchy to get from one element to the other.
```
<div>
  <div>
    <b id="elem"></b>
  </div>
  <code id="anchor"></code>
</div>
```
The HTML-element with id "elem" has a distance of 3 to the anchor element.
But if two elements require the exact same amount of steps to reach from an anchor element,
the element that comes first in the html source code is determined to be nearer to the anchor.
```
<div>
  <div>
    <b id="elem0">elem</b>
    <b id="elem1">elem</b>
  </div>
  <code id="anchor"></code>
</div>
```
In the above example the element with id "elem0" is nearer to the anchor than the element with id "elem1".
Further Examples:
```
<div>
    <b id="elem0">elem</b>
    <b id="elem1">elem</b>
    <code id="anchor"></code>
</div>
```

```
<div>
    <b id="elem0">elem0</b>
</div>
<div>
    <b id="elem1">elem1</b>
</div>
<div>
    <code id="anchor">anchor</code>
</div>
```
Again, according to the current implementation `elem0`is "nearer" to the `anchor` element.

Should we change the implementation, so that when two elements have the same minimal path to reach the anchor element, the element is "nearer", that is also nearer in the HTML-source?

**Comment by svettwer** [comment]
In discussion with @tnobody, the edge case described in this issue is not known and not intended as there is no test specifying this particular behavior. 

Planned steps:
- Change the specification to reflect the correct behavior
- Open a Bug ticket to change the implementation

As `_near` is a rarely used relation, the fix of this edge case has low priority. Nevertheless, it is good to know that it exists. :+1:
