### ISSUE TITLE
Sakuli CLl encrypt command fails when secret is a numerical value

### ISSUE THREAD

**Issue by tnobody** [sakuli/sakuli#587]
**Version**

2.4.0

**Short overview**

Running

`npx sakuli encrypt "123456" --masterkey <KEY>`

Fails with the following message:

```bash
node_modules found: /Users/timkeiner/Projects/consol/TA/asfinag/asfinag_s2/node_modules,/usr/local/lib/node_modules
Sakuli presets found during auto discovery: @sakuli/legacy
No sakuli preset configuration in package.json found
Loading Sakuli with @sakuli/legacy
  ____            _              _   _ 
 / ___|    __ _  | | __  _   _  | | (_)
 \___ \   / _` | | |/ / | | | | | | | |
  ___) | | (_| | |   <  | |_| | | | | |
 |____/   \__,_| |_|\_\  \__,_| |_| |_|
                                       
========================================

An error occured: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (123456)
```

**Detailed error description**

**Steps to reproduce error**

Try to encrypt a numerical value (e.g. some PIN) with `sakuli encrypt`

**Additional content**

It seems that numerical CLI arguments are automatically parsed not (runtime-) typed checked until they are passed to the actual encryption function.

**Comment by cliffle** [comment]
To pin the input as `string`, add a `type: "string"` option to the `positional`
https://github.com/sakuli/sakuli/blob/00ea93d8cb0db4185262102b8657b4bd7ba5aa82/packages/sakuli-legacy/src/encrypt-command/encrypt-command.class.ts#L13-L15
