### ISSUE TITLE
_wait should return the value of the awaited expression

### ISSUE THREAD

**Issue by tnobody** [sakuli/sakuli#596]
**Short overview**

As a Testauthor I want to obtain the result value of the `expression` from an `_wait` call to avoid the invocation of this expression another time.

Currently `_wait` returns a `Promise<void>` under any circumstances

Proposed interface:

```typescript
type _wait = <T>(millis: number, expression?: () => Promise<T>)): Promise<T>
```

**Use case**

This is useful for expensive operations to avoid unnecessary calls:

```typescript
  const region = await _wait(4000, () => _getRegionByText("Overview Console"))
  // region is now the result of _getRegionByText or the entire expression throws
```

**Detailed description**

`_wait` should consider catching errors of the expression handle them as falsy values

**Comment by svettwer** [comment]
`type _wait = <T>(millis: number, expression?: () => Promise<T>)): Promise<T>`

This interface is unfortunately insufficient from my perspective. Because as ` expression?` is optional, what object of `T` should we return? At least, a `T | undefined`-ish interface would be required so that we don't break the contract of the API.

**Comment by tnobody** [comment]
@svettwer you are absolutely right. This type is missing some details and was more meant as a sketch to show the basic Idea.

A more detailed definition was a bit to verbose for me at this point:

```typescript
type WaitParameterTimeoutOnly = [number]
type WaitParameterWithExpression<T> = [number, () => Promise<T>]
type WaitPararmeter<T> = WaitParameterTimeoutOnly | WaitParameterWithExpression<T>
declare const _wait: <P extends WaitPararmeter<any>>(...params: P) => P extends WaitParameterWithExpression<infer R> ? Promise<R> : Promise<void>

``` 

Here is a [Playground with a tested example](https://www.typescriptlang.org/play?#code/PTAEBUE8AcFNQIYGcmwE4BcCWB7AdqABawA2caoAZmjgLZEYbRIBcIATAiVhpAHQBjOsHYAGAIwBOYKIDswDLCTY8AcwC0yhNgHrecJH0IZaJAFD74AQRToMAUQCOAVy4AecABpQ9gB5wBRQATAD5QAF4zUAhQWF9FPCCkH39YQNggqNAAflAACj8A4Nj42ETk8BzQDDRneBZQPFgAN3QASiyGpta0AG4zAYsYeAB1BB4ABQQ0BFpYRTRwLDmcZwwAeTwSSAjQAG08Z1oAI3QAXSG4UDHJ6dn59BGeQkK0JSRcPA8w8P3Dk-Q3jybQiYQmNFoWFQ3wulmu4wwUxmaDmC2+uxuiLuqPQSxWa0221AAB94bcZji0E8MC9-G8UJ9vmYgmkSNN4EI8MpQAB9ADuCIabgmJQSSTJWORlLcCDwkBCITyfGV0GxrFAExB4TBorK4sxSPuC2ptOg9I++DcWDwlHQoAASmFcuC6FDYG5HaAGi7IdDmjgsKEBnlkJA8AJ8lqwgBvAbRaKc7loADKNWtql2CAFPF52YweXE3lD4cjoNAACIABKkEg4a44NAkILljrx0CJjCgNAANQDQUzedzCILHSy0RI8y7qbQ6eThFWTYAQrArNP0w0bKhME5XCQ3JYcJQp2m1N5lDO1D9qrVYP02xPOz2+3OF0Fl73AxvbNuXO4D0en0Dbx-UDK8ajqfozAAXzaIA)

**Comment by svettwer** [comment]
awesome! Thx for designing that! :rocket:
