### ISSUE TITLE
scrollIntoView for web actions

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#92]
**Short overview**
Before executing web actions like `_click`, the desired element should be scrolled into view.

**Use case**
When not scrolled into view, Selenium is not able to click the element.

**Detailed description**
When locating an element outside the current viewport, Selenium is not able to perform actions like click etc. on it. Right now, scrolling has to be done manually, which is quite error prone. By utilising browser support for `element.scrollIntoView()`, we could avoid manual scrolling.

**Additional content**
> Please provide any (mandatory) additional data for your enhancement

**Comment by ZNicoZ** [comment]
As a temporary workaround _focus before a _click works fine.

**Comment by sni** [comment]
i usually also do a `mousemove()` or `_mouseOver` before the `_click`, because thats what a user would do usually and things sometimes behave different if the mouse hovers things.
I would not put too much magic into `_click` but instead provide some convenience wrappers like:
```
function ... {
  scrollintoview()
  mouseover()
  isVisible()
  highlight()
  click()
}
```

**Comment by tnobody** [comment]
For now the work around with `_focus()` should be sufficient for the Legacy-DSL. 
In the future DSL might provide some transparent mechanism to let the user decide if he wants the element scroll into the view (maybe a parameter, error-handler or convenience function.

What we definitely should do is to document this.
