### ISSUE TITLE
Case/Step/Command Reporting

### ISSUE THREAD

**Issue by sni** [sakuli/sakuli#93]
**Short Description**
It would be helpful to hook into steps/cases and even commands to create custom forwarder on each line/step/case of the testcase.

**Use case**
Create custom forwarder to submit intermediate results or use sakuli as unit tests with detailed output.

**Comment by tnobody** [comment]
Thank you for this issue.
While implementing #64 we extended the TestExecutionContext to emit detailed events when Execution/Suite/Case/Step/Actions Starts/Ends.

Right now the "Problem" is, that the [Forwarder-interface method `forward`](https://github.com/sakuli/sakuli/blob/a9ce9d7e53ed1b6ffb44f583cad9b1fd876ac92a/packages/sakuli-core/src/forwarder/forwarder.interface.ts#L5) is invoked at the end of an execution which makes this events useless for this use-case. 

@s1hofmann what do you think about extending the forwarder interface with (optional) methods like `afterSuite` `afterCase`...?

**Comment by tnobody** [comment]
As discussed with @s1hofmann we will extend forwarder interface to handle immediate results while execution
