### ISSUE TITLE
Avoid Boilerplate for Simple Tests

### ISSUE THREAD

**Issue by sni** [sakuli/sakuli#94]
**Short overview**
A simple test would be as short as:
_open_url("....")
_is_visible...

**Use case**
DRY is valid for tests as well. Repeating boilerplate code should be avoided if possible.

**Comment by tnobody** [comment]
Thank you for this issue, we work on an alternative/new DSL which will focus on reducing boilerplate as well as configuration.

**Comment by svettwer** [comment]
Closed in favor of #244
