### ISSUE TITLE
Global installation for system wide node installation

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli#95]
**Version**
2.0.0

**Short overview**
`sudo npm i -g @sakuli/cli` fails due to missing permissions for system wide node installation

**Detailed error description**
When trying to install Sakuli as a global package on a system wide node installation via `sudo npm i -g @sakuli/cli`, the installation process fails due to missing filesystem permission.
Reason for this is the additional install step for the platform dependent OpenCV package, which lacks sufficient privileges.

A possible workaround would be a migration from the current installation process for platform dependent packages to optional dependencies, which are flagged for the respective target platform.

**Comment by tnobody** [comment]
What kind of permissions are required for the OpenCV installation?
Is it the OpenCV package itself which is causes this?

**Comment by s1hofmann** [comment]
Should be resolved with #111
