### ISSUE TITLE
getClipboard returns a Promise, log-output should be improved

### ISSUE THREAD

**Issue by ZNicoZ** [sakuli/sakuli#99]
**Version**
2.0.0
**Short overview**
Sakulis clipboard functionalities don´t seem to work
**Steps to reproduce error**
```
(async () => { 
    const testCase = new TestCase(); 
    const url = "https://sakuli.io";
    const env = new Environment();
    try {
        await _navigateTo(url + "/enterprise");
        env.setClipboard("################hello world");
        Logger.logInfo("This is from getClipboard: " + env.getClipboard());

    } catch (e) {
        await testCase.handleException(e); 
    } finally {
        await testCase.saveResult(); 
    }
})().then(done); 
```
Output in Logfile:
```
[Wed May 29 2019 23:41:55 GMT+0200 (GMT+02:00)] INFO Setting clipboard content: '################hello world'
[]
[Wed May 29 2019 23:41:55 GMT+0200 (GMT+02:00)] INFO Clipboard content: '[object Promise]'
[]
[Wed May 29 2019 23:41:55 GMT+0200 (GMT+02:00)] INFO This is from getClipboard: [object Promise]
```

**Comment by tnobody** [comment]
getClipboard returns a Promise (async value).

What happens if you change 8th line to

```javascript
Logger.logInfo("This is from getClipboard: " + await env.getClipboard());
``

**Comment by ZNicoZ** [comment]
The await in front of env.getClipboard() did the trick.
```
[]
[Thu May 30 2019 10:43:02 GMT+0200 (GMT+02:00)] INFO Setting clipboard content: '################hello world'
[]
[Thu May 30 2019 10:43:02 GMT+0200 (GMT+02:00)] INFO Clipboard content: '[object Promise]'
[]
[Thu May 30 2019 10:43:02 GMT+0200 (GMT+02:00)] INFO This is from getClipboard: ################hello world
[]
[Thu May 30 2019 10:43:02 GMT+0200 (GMT+02:00)] INFO Finished Execution
```
Internally this should be done as well, as the log output 
`[Thu May 30 2019 10:43:02 GMT+0200 (GMT+02:00)] INFO Clipboard content: '[object Promise]'`
is being triggered and generated when using 
`await env.getClipboard();`

**Comment by tnobody** [comment]
@s1hofmann 
Is it a good idea at all to log the data in the clipboard? With respect to sensitive data we should make such a behavior opt-in (or remove it completely)

**Comment by s1hofmann** [comment]
Agreed 👍
For consistency with other legacy API methods, I'd suggest to introduce separate methods like e.g. `getClipboardMasked()`.
In future APIs, I'd prefer something like a `debug` flag to configure logging behaviour for a test.
